### ISSUE TITLE
Cant add bulk users into panel

### ISSUE THREAD

**Issue by click23** [hossinasaadi/x-ui#100]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hi I need to bulk add users into profiles.
Also after adding the log and multiuser method Xray FAILS.

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by hossinasaadi** [comment]
Hi @click23 ,first : for now we cant add bulk add user
sec : you do it wrong, config is json type

**Comment by hossinasaadi** [comment]
Hi @click23 ,first : for now we cant add bulk add user
sec : you do it wrong, config is json type
