### ISSUE TITLE
مشکل با پروتکل تروجان

### ISSUE THREAD

**Issue by moslem2013** [hossinasaadi/x-ui#103]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام وقت بخیر پروتکل تروجان رو راه انداختم ولی یک مشکلی وجود داره موقعی پروتکل تروجان رو ایجاد میکنم 
بعد از اینکه بارکد رو اسکن میکنم یا روی کپی لینک کلیک میکنم میاد ایپی سرور رو تحویل میده با اینکه Tls فعال هستش 
ممنون میشم این موارد رو بررسی و حل کنید

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by Recoba86** [comment]
update to the last version
and for login to the panel use domain instead of IP!
