### ISSUE TITLE
this version does not restart the users trafic. it just restart total trafic

### ISSUE THREAD

**Issue by m2tts2001** [hossinasaadi/x-ui#106]

**Comment by m2tts2001** [comment]
I updated to V0.5.3 and still could not restart the client traffic. I mean could not reset the counter for each client. Now we can just add to previous traffic. For example, if a client uses 5Gb, we could not make it zero.
![image](https://user-images.githubusercontent.com/116441039/203275155-e9a1f247-aa84-409b-8287-d4d2ca3408d9.png)

**Comment by amihos** [comment]
> I updated to V0.5.3 and still could not restart the client traffic. I mean could not reset the counter for each client. Now we can just add to previous traffic. For example, if a client uses 5Gb, we could not make it zero.
> ![image](https://user-images.githubusercontent.com/116441039/203275155-e9a1f247-aa84-409b-8287-d4d2ca3408d9.png)
> 

Update to the newest version and you get this![Screenshot_20221122-234639.jpg](https://user-images.githubusercontent.com/35190548/203412868-f58cffb8-ef5f-434a-821b-31e1e53b66ab.jpg)
