### ISSUE TITLE
مشکل دریافت اطلاعات کاربر در ربات

### ISSUE THREAD

**Issue by SepidGsm** [hossinasaadi/x-ui#114]
سلام . ممنون از قابلیتی که اضافه کردین
با این دستور 
/usage  fc3239ed-8f3b-4151-ff51-b183d5182142
پیغام something wrong! نمایش داده میشه . در حالی که uid موجوده
مشاهده جزئیات کاربر با وارد کردن uid برای کاربر سخت هست اگر با وارد کردن پورت باشه عالی میشه

**Comment by amihos** [comment]
> سلام . ممنون از قابلیتی که اضافه کردین
> با این دستور 
> /usage  fc3239ed-8f3b-4151-ff51-b183d5182142
> پیغام something wrong! نمایش داده میشه . در حالی که uid موجوده
> مشاهده جزئیات کاربر با وارد کردن uid برای کاربر سخت هست اگر با وارد کردن پورت باشه عالی میشه
> 

با پورت نمیشه چون در حال حاضر این ویژگی برای client های موجود روی یک inbound که همگی یک پورت دارن کار می‌کنه. پس وجه تمایز باید چیزی غیر از پورت باشه

**Comment by SepidGsm** [comment]
من با پورتهای متفاوت اکانت میسازم و اکثرا هم اینطوریه
میشه ورودی رو انتخابی گذاشت . هم با پورت هم uid

**Comment by hossinasaadi** [comment]
> من با پورتهای متفاوت اکانت میسازم و اکثرا هم اینطوریه میشه ورودی رو انتخابی گذاشت . هم با پورت هم uid

set unique email for every client (id) and check it

**Comment by SepidGsm** [comment]
برای گزارشگیری با پورت راهنمایی میکنین ؟
من یوزر با پورت یکسان ندارم
