### ISSUE TITLE
Tunnel (bridge server)

### ISSUE THREAD

**Issue by NotMRGH** [hossinasaadi/x-ui#118]
من از تانلینگ استفاده میکنم برای همین IP Limit کار نمیکنه راهی دارید ک مشکلم حل شه

نمیشه خود xray-core روی یک سرور دیگه باشه x-ui  روی یکی دیگه؟ به هم وصلشون کرد؟

**Comment by sharifiamin** [comment]
سلام. خود xray-core قابلیت این رو داره که inbound و outbound رو هر چی بخواید تعریف کنید. من حدس میزنم میشه رو سرور اول که با کاربر در ارتباط هست همین پنل رو نصب کرد ولی outbound رو فرستاد روی ip سرور دوم. بجای اینکه outbound روی پروتکل freedom باشه.

**Comment by hossinasaadi** [comment]
look you need somethin like this :
` client <--> bridge Server <-->  upstream Server <-->  free internet 
`
run x-ui on your bridge server and edit config outbound like this :
```json
  "outbounds": [
   {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "UPSTREAM_IP",
          "port": UPSTREAM_PORT,
          "users": [
            {
              "id": " UPSTREAM_UUID",
              "alterId": 10,
              "security": "auto"
            }
          ]
        }
      ]
    },
    "streamSettings":{
      "network":"ws"
    }

},
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
```
in the upstream server, you can run x-ui or any v2ray and create vmess and put in top requirements

**Comment by NotMRGH** [comment]
دیگه نیاز نیست توی هردوتا سرور یوزر بسازیم؟


We don't need to create users in both servers anymore?

**Comment by hossinasaadi** [comment]
nope

> دیگه نیاز نیست توی هردوتا سرور یوزر بسازیم؟
> 
> We don't need to create users in both servers anymore?

**Comment by NotMRGH** [comment]
What is UPSTREAM_PORT and UPSTREAM_UUID?

**Comment by sharifiamin** [comment]
> What is UPSTREAM_PORT and UPSTREAM_UUID?

شما n تا سرور هم میتونید زنجیر کنید بهم. روی سرور اول یوزر ها رو تعریف میکنید که کاربرها وصل میشن. روی سرور بعدی xray نصب میشه و هر چند تا پورت که خواستید باز میکنید یعنی اکانت میسازید. رو سرور اول ترافیک کاربرها رو ارجاع میدید به سرور دوم. UPSTREAM_UUID منظور اکانت سرور دوم هست. UPSTREAM_PORT منظور پورت سرور دوم که باز کردید. 

میتونید بار رو توزیع کنید رو سرورهای مختلف یا ادغام کنید
میتونید تو قسمت routing با "geoip:ir"  ترافیک سایت های داخلی رو جدا کنید و پروتکلش رو بزنید  direct و دیگه رو سرور خارجی نفرستید و مابقی رو بفرستید برا سرور دوم.
حتی میتونید تو تنظیم client ، ترافیک داخل رو direct بزنید که اصلا به سرور اول هم نفرسته :))
بینهایت قابلیت داره v2ray
https://guide.v2fly.org/en_US/basics/routing/cndirect.html#client-side
https://www.v2fly.org/en_US/guide/workflow.html#single-server-mode

**Comment by hossinasaadi** [comment]
@sharifiamin  god bless you, i close the issue.

**Comment by nursemazloom** [comment]
> look you need somethin like this : `client <--> bridge Server <--> upstream Server <--> free internet ` run x-ui on your bridge server and edit config outbound like this :
> 
> ```json
>   "outbounds": [
>    {
>     "protocol": "vmess",
>     "settings": {
>       "vnext": [
>         {
>           "address": "UPSTREAM_IP",
>           "port": UPSTREAM_PORT,
>           "users": [
>             {
>               "id": " UPSTREAM_UUID",
>               "alterId": 10,
>               "security": "auto"
>             }
>           ]
>         }
>       ]
>     },
>     "streamSettings":{
>       "network":"ws"
>     }
> 
> },
>     {
>       "protocol": "freedom",
>       "settings": {}
>     },
>     {
>       "protocol": "blackhole",
>       "settings": {},
>       "tag": "blocked"
>     }
>   ],
> ```
> 
> in the upstream server, you can run x-ui or any v2ray and create vmess and put in top requirements

سلام مرسی بابت روشی که معرفی کردین فقط من برای هر یوزر پورت جداگانه میذارم باید چجوری این کانفیگ رو تنظیم کنم که برای یوزر ها وقتی داخل برنامه تعریفشون میکنم داخل فایل کانفیگ بصورت خودکار پورت و Uuid تنظیم بشه داخلش؟

**Comment by NotMRGH** [comment]
انجام دادم ولی نشد

**Comment by nursemazloom** [comment]
آقا اگه کسی چیزی بلده لطفا این مشکل ما رو حل کنید واقعا الان نصف کسایی که میخوان آی پی رو محدود کنند نمیتونن چون دارن از سرور واسط استفاده میکنن یه نفر که میدونه بیاد این کانفیگ رو هم بذاره جای دوری نمیره😥

**Comment by testme1236** [comment]
> آقا اگه کسی چیزی بلده لطفا این مشکل ما رو حل کنید واقعا الان نصف کسایی که میخوان آی پی رو محدود کنند نمیتونن چون دارن از سرور واسط استفاده میکنن یه نفر که میدونه بیاد این کانفیگ رو هم بذاره جای دوری نمیره😥 این تاپیکم فک کنم هنوز حل نشده که بستینش چون کسی نتونسته این روش رو اجرا کنه

شما باید روی هردو سرور داخل ایران و خارج ایران پنل رو راه اندازی کنی 
یوزرها رو داخل پنل سرور ایران میسازی و لینک اتصال رو بهشون میدی اینجوری اول ایپی هاشون بدون تونل شدن به سرور ایران میرسه و محدود میشه
تا اینجا به اینترنت عادی(فیلتر) متصل شدن الان باید سرور ایران رو به سرور خارج ایران متصل کنی
روی پنل خارج ایران یه یوزر میسازی با پروتکل vmess و alterid رو 10 میذاری با ws اینجا یه پورت و یه UUID بهت میده
 اونا رو داخل کانفیگ xray پنل ایران قرار میدی تا پنل ایران به سرور خارج ایران متصل بشه
فرض کن ایپی سرور خارج ایران 10.20.30.40 باشه داخل تنظیمات پنل ایران باید اینا رو جایگزین کنی به جای
UPSTREAM_IP : 10.20.30.40 آیپی سرور خارج
UPSTREAM_PORT : 1234 پورت اکانتی که روی سرور خارج ساختی
UPSTREAM_UUID : 18e10b4b-f993-4345-9c9e-de3f3d165f31 اینم از داخل پنل خارج کپی کن بزن تو کانفیگ پنل ایران

  "outbounds": [
   {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "10.20.30.40",
          "port": 1234,
          "users": [
            {
              "id": "18e10b4b-f993-4345-9c9e-de3f3d165f31",
              "alterId": 10,
              "security": "auto"
            }
          ]
        }
      ]
    },
    "streamSettings":{
      "network":"ws"
    }

},
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  
 بعد از ذخیره کردن تغییرات داخل پنل ایران سرور ایران به سرور خارج ایران متصل میشه و به اینترنت آزاد(بدون فیلتر) وصل شدی

**Comment by NotMRGH** [comment]
> 

داداش این کانفیگ منه ولی نمیشه
``
{
  "log": {
    "loglevel": "warning", 
    "access": "./access.log"
  },
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
    "outbounds": [
   {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "UP_EU",
          "port": PORT_EU,
          "users": [
            {
              "id": "UUID_EU",
              "alterId": AFTERID_EU,
              "security": "auto"
            }
          ]
        }
      ]
    },
    "streamSettings":{
      "network":"ws"
    }

},
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },

    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}
``

**Comment by EminShahbazi** [comment]
این روش باعث افت سرعت میشه؟

**Comment by nursemazloom** [comment]
> > آقا اگه کسی چیزی بلده لطفا این مشکل ما رو حل کنید واقعا الان نصف کسایی که میخوان آی پی رو محدود کنند نمیتونن چون دارن از سرور واسط استفاده میکنن یه نفر که میدونه بیاد این کانفیگ رو هم بذاره جای دوری نمیره😥 این تاپیکم فک کنم هنوز حل نشده که بستینش چون کسی نتونسته این روش رو اجرا کنه
> 
> باید روی هردو سرور داخل ایران و خارج ایران پنل رو راه اندازی کنی یوزرها رو داخل پنل سرور ایران میسازی و لینک اتصال رو بهشون میدی اینجوری اول ایپی هاشون بدون تونل شدن به سرور ایران میرسه و محدود میشه تا اینجا به اینترنت عادی(فیلتر) متصل شدن الان باید سرور ایران رو به سرور خارج ایران متصل کنی روی پنل خارج ایران یه یوزر میسازی با پروتکل vmess و alterid رو 10 میذاری با ws اینجا یه پورت و یه UUID بهت میده اونا رو داخل کانفیگ xray پنل ایران قرار میدی تا پنل ایران به سرور خارج ایران متصل بشه فرض کن ایپی سرور خارج ایران 10.20.30.40 باشه داخل تنظیمات پنل ایران باید اینا رو جایگزین کنی به جای UPSTREAM_IP : 10.20.30.40 آیپی سرور خارج UPSTREAM_PORT : 1234 پورت اکانتی که روی سرور خارج ساختی UPSTREAM_UUID : 18e10b4b-f993-4345-9c9e-de3f3d165f31 اینم از داخل پنل خارج کپی کن بزن تو کانفیگ پنل ایران
> 
> ```
>   "outbounds": [
>    {
>     "protocol": "vmess",
>     "settings": {
>       "vnext": [
>         {
>           "address": "10.20.30.40",
>           "port": 1234,
>           "users": [
>             {
>               "id": "18e10b4b-f993-4345-9c9e-de3f3d165f31",
>               "alterId": 10,
>               "security": "auto"
>             }
>           ]
>         }
>       ]
>     },
>     "streamSettings":{
>       "network":"ws"
>     }
> 
> },
>     {
>       "protocol": "freedom",
>       "settings": {}
>     },
>     {
>       "protocol": "blackhole",
>       "settings": {},
>       "tag": "blocked"
>     }
>   ],
>   
> ```
> 
> بعد از ذخیره کردن تغییرات داخل پنل ایران سرور ایران به سرور خارج ایران متصل میشه و به اینترنت آزاد(بدون فیلتر) وصل شدی

خب من دقیقا همین کار شما که گفتین رو امتحان کردم ولی بازم جواب نگرفتم و محدودیت داشتم

**Comment by mrtaj95** [comment]
متاسفانه برای من هم محدودیت آیپی کار نمیکنه.
 رو هر دو سرور نصب کردم و محدودیت آیپی رو هم رو ۱ گذاشتم ولی با سه تا دستگاه (با سیمکارت های مختلف رایتل و ایرانسل) وصل شدم اما یوزر رو غیر فعال نکرد.
با اینکه تو لیست آیپی ها دو تا آیپی رو نشون میداد.

**Comment by sydalihosini** [comment]
> متاسفانه برای من هم محدودیت آیپی کار نمیکنه. رو هر دو سرور نصب کردم و محدودیت آیپی رو هم رو ۱ گذاشتم ولی با سه تا دستگاه (با سیمکارت های مختلف رایتل و ایرانسل) وصل شدم اما یوزر رو غیر فعال نکرد. با اینکه تو لیست آیپی ها دو تا آیپی رو نشون میداد.

ببینید اینطور که من متوجه طرز کار اسکریپت شدم اگر دستگاه اول پکتی ارسال نکنه دستگاه دوم کانکت میشه اگر دستگاه دوم پکتی ارسال نکنه دستگاه دوم متصل میشه اینطوری فرض کن که دستگاه اول میزنه رو دانلود تا پایان دانلود دستگاه دوم هیچ جوره امکان وصل شدن رو نداره چون مداوم با سرور درحال ارسال و دریافت هست حالا اگر یه لحظه کوتاه نت دستگاه اول قطع بشه و دستگاه دوم متصل بشه و بزنه رو دانلود حالا تا پایان دانلود دستگاه اول نمیتونه وصل بشه :)

**Comment by mrtaj95** [comment]
> > متاسفانه برای من هم محدودیت آیپی کار نمیکنه. رو هر دو سرور نصب کردم و محدودیت آیپی رو هم رو ۱ گذاشتم ولی با سه تا دستگاه (با سیمکارت های مختلف رایتل و ایرانسل) وصل شدم اما یوزر رو غیر فعال نکرد. با اینکه تو لیست آیپی ها دو تا آیپی رو نشون میداد.
> 
> ببینید اینطور که من متوجه طرز کار اسکریپت شدم اگر دستگاه اول پکتی ارسال نکنه دستگاه دوم کانکت میشه اگر دستگاه دوم پکتی ارسال نکنه دستگاه دوم متصل میشه اینطوری فرض کن که دستگاه اول میزنه رو دانلود تا پایان دانلود دستگاه دوم هیچ جوره امکان وصل شدن رو نداره چون مداوم با سرور درحال ارسال و دریافت هست حالا اگر یه لحظه کوتاه نت دستگاه اول قطع بشه و دستگاه دوم متصل بشه و بزنه رو دانلود حالا تا پایان دانلود دستگاه اول نمیتونه وصل بشه :)

تو پنل که نوشته بعد از اینکه یوزر غیرفعال شد٬ قبل از اینکه دوباره فعال کنید لاگ آیپی رو خالی کنید. به نظرم بهتره یوزر غیرفعال شه. الات من با سه دستگاه همزمان بدون هیچ مشکلی از اینستا و یوتیوب استفاده میکنم.
فقط بعضی وقتا یکی از دستگاه (فقط هم همین دستگاه خاص) نتش قطع میشه و دیگه تا چند ثانیه حتی به یوزرهای دیگه هم وصل نمیشه.
@hossinasaadi راهی نیست که یوزر غیرفعال شه؟

**Comment by sydalihosini** [comment]
> > > متاسفانه برای من هم محدودیت آیپی کار نمیکنه. رو هر دو سرور نصب کردم و محدودیت آیپی رو هم رو ۱ گذاشتم ولی با سه تا دستگاه (با سیمکارت های مختلف رایتل و ایرانسل) وصل شدم اما یوزر رو غیر فعال نکرد. با اینکه تو لیست آیپی ها دو تا آیپی رو نشون میداد.
> > 
> > 
> > ببینید اینطور که من متوجه طرز کار اسکریپت شدم اگر دستگاه اول پکتی ارسال نکنه دستگاه دوم کانکت میشه اگر دستگاه دوم پکتی ارسال نکنه دستگاه دوم متصل میشه اینطوری فرض کن که دستگاه اول میزنه رو دانلود تا پایان دانلود دستگاه دوم هیچ جوره امکان وصل شدن رو نداره چون مداوم با سرور درحال ارسال و دریافت هست حالا اگر یه لحظه کوتاه نت دستگاه اول قطع بشه و دستگاه دوم متصل بشه و بزنه رو دانلود حالا تا پایان دانلود دستگاه اول نمیتونه وصل بشه :)
> 
> تو پنل که نوشته بعد از اینکه یوزر غیرفعال شد٬ قبل از اینکه دوباره فعال کنید لاگ آیپی رو خالی کنید. به نظرم بهتره یوزر غیرفعال شه. الات من با سه دستگاه همزمان بدون هیچ مشکلی از اینستا و یوتیوب استفاده میکنم. فقط بعضی وقتا یکی از دستگاه (فقط هم همین دستگاه خاص) نتش قطع میشه و دیگه تا چند ثانیه حتی به یوزرهای دیگه هم وصل نمیشه. @hossinasaadi راهی نیست که یوزر غیرفعال شه؟

بهتره که این محدودیت خاص اجرا نشه چون بالاخره یه فردی که وصل میشه یک ایپی ثابت نخواهد داشت مثلا میره رو نت همراه میره رو نت مودم یا میره جایی به مودم اونجا کانکت میشه 3 تا ایپی مختلف شد این که دچار مشکل میکنه هر شخصی رو

**Comment by nursemazloom** [comment]
به نظرم اگه بحث رو منحرف نکنیم بهتره چون اینجا داشتن در مورد تونل کردن سرور ایران بحث میکردن
اگه دوستان روشی رو بلدن که سرور ها رو درست به هم تونل کنیم تا بشه ازین سیستم با عبور از سرور ایران استفاده کرد

**Comment by AuthorShin** [comment]
> look you need somethin like this : `client <--> bridge Server <--> upstream Server <--> free internet ` run x-ui on your bridge server and edit config outbound like this :
> 
> ```json
>   "outbounds": [
>    {
>     "protocol": "vmess",
>     "settings": {
>       "vnext": [
>         {
>           "address": "UPSTREAM_IP",
>           "port": UPSTREAM_PORT,
>           "users": [
>             {
>               "id": " UPSTREAM_UUID",
>               "alterId": 10,
>               "security": "auto"
>             }
>           ]
>         }
>       ]
>     },
>     "streamSettings":{
>       "network":"ws"
>     }
> 
> },
>     {
>       "protocol": "freedom",
>       "settings": {}
>     },
>     {
>       "protocol": "blackhole",
>       "settings": {},
>       "tag": "blocked"
>     }
>   ],
> ```
> 
> in the upstream server, you can run x-ui or any v2ray and create vmess and put in top requirements

@hossinasaadi How to set it up with Vless?

**Comment by sharifiamin** [comment]
@nursemazloom  @NotMRGH 
دوستانی که دو تا سرور دارند و مشکل دارند کانفیگ هر دو سرور و کلاینت رو بزارند و دلیل مشکلشون رو کامل توضیح بدند.

اصول کلی کانفیگ xray برای همه دستگاه ها از client گرفته تا سرور اول و دوم یکسانه
کلا inbound ها تعریف میکنه که ترافیک چطور بیاد به xray مثلا از یوزرها بیاد یا از local host
و outbound ها تعریف میکنه ترافیک بعد خروج از xray کجا بره مثلا مستقیم بره تو اینترنت یا بره سرور دوم 
هر outbound یک tag داره و routing تعریف میکنه چه بخشی از ترافیک به کدوم tag هدایت بشه
اگر routing تعریف نشه پیش فرض outbound اولی برا همه ترافیک انتخاب میشه

تو سایت v2ray.com و v2fly.org کامل توضیح داده فقط یک کم دقت میخواد

**Comment by sharifiamin** [comment]
@sydalihosini 
باید کانفیگ ها رو attach کنید تا مشکل مشخص بشه.
وقتی شما ترافیک سرور اول رو میفرستید برا سرور دوم ، باید روی سرور دوم یک اکانت نامحدود بسازید. رو سرور اول outbound را روی اون ip و port و UUID تنظیم کنید. اونوقت سرور اول حکم client رو داره برا سرور دوم. روی خود سرور اول اکانت میسازید برا کاربرها. روی سرور دوم outbound تنظیم میشه بصورت freedom direct که مستقیم میفرسته رو اینترنت.
