### ISSUE TITLE
Multi-User Usage Bug

### ISSUE THREAD

**Issue by rasolebadat** [hossinasaadi/x-ui#123]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

Hello Dear @hossinasaadi, I've tried to change Emails from Multi-User Inbound and after I change Email the Usage will get reset as you can see from the below Images.
![image](https://user-images.githubusercontent.com/118859720/203671496-d6cf25bc-e0f2-4901-add2-92d594c2b51e.png)
![image](https://user-images.githubusercontent.com/118859720/203671615-9033c6f1-ae20-4f80-8e5c-1834e109abb1.png)

👍 ❤️ 

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by sharifiamin** [comment]
i confirm this bug.
even when you delete all accounts , all emails still exist in Database & those emails cant be used anymore.
if i use old email to create new account , traffic usage is not working . console return UNIQUE EMAIL ERR.

**Comment by hossinasaadi** [comment]
This isn’t a bug, email is an unique key in database and you can’t change it when you create user, cus all data retrieved by email. If you change it , it assigns as new user.

**Comment by sharifiamin** [comment]
> This isn’t a bug, email is an unique key in database and you can’t change it when you create user, cus all data retrieved by email. If you change it , it assigns as new user.

there is a problem sir.
suppose you create an account for ali@gmail for 1 month.
six month later ali want a new account.
you create new account using ali@gmail but it cant be activated -> UNIQUE EMAIL ERR.
there should be a way to delete ali@gmail from database when account itself deleted five month ago.
anyway if you create account by new UUID & ali@gmail , user can connect but traffic show 0 KB.
