### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR on port web panel

### ISSUE THREAD

**Issue by IamYousef** [hossinasaadi/x-ui#126]
I receive `ERR_SSL_PROTOCOL_ERROR` when trying to connect to my x-ui web panel. Does anyone have any solution?

![Screenshot_20221124-123259_Chrome.png](https://user-images.githubusercontent.com/22050119/203740969-dc2c926d-cc4b-450f-b050-55b61f12ccfa.png)

**Comment by hossinasaadi** [comment]
Its not an issue, please search in web!
