### ISSUE TITLE
Xray-Core 1.6.5 wrong version

### ISSUE THREAD

**Issue by amir215909** [hossinasaadi/x-ui#127]
In [your xray-core 1.6.5](https://github.com/hossinasaadi/Xray-core/releases/tag/1.6.5) amd64 version, `-version` option shows that xray-core version is 1.6.4 even though it is version 1.6.5 which also shows wrong version in xui panel (uses `-version` option of xray-core binary).

![Screenshot from 2022-11-24 12-45-53](https://user-images.githubusercontent.com/25514831/203744552-db70a984-c8fb-415c-b86b-02937cd7b147.png)

**Comment by hossinasaadi** [comment]
Please first of all check other issues.

**Comment by amir215909** [comment]
What do you mean check other issues? This bug is not reported.
