### ISSUE TITLE
X-ui crashes and doesn't work

### ISSUE THREAD

**Issue by m2tts2001** [hossinasaadi/x-ui#130]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

X-ui panel hangs every day and doesn't work and then all configs don't work until I restart the server or x-ui. I don't know why. But I have several servers and it happens in all of them especially when the traffic and load on the server is high for example in the evening and night. 
I think it is good if the panel has self restart for exemple in each hour or the admin could set it. 

### Version of x-ui

<details>

```console
$ x-ui version latest
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```
Nothing
</details>

**Comment by hossinasaadi** [comment]
Why you don’t fill x-ui log and x-ui version?
