### ISSUE TITLE
Cannot update/switch to xray v1.6.5

### ISSUE THREAD

**Issue by Mo3M** [hossinasaadi/x-ui#145]
### Welcome

- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

As the title says switching to v1.6.5 shows "install xray success" but nothing really happens.
Thanks

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by amir215909** [comment]
It actually switches to 1.6.5 but the version of application is not changed to 1.6.5 from 1.6.4, [An issue](https://github.com/hossinasaadi/x-ui/issues/127#issue-1463016780) was opened for this, but for some reason it is closed.
If you sha256sum xray-core 1.6.5, and 1.6.4 you will see they are different binaries.
