### ISSUE TITLE
انتقال دادن یوزر ها از یک سرور به سرور دیگر

### ISSUE THREAD

**Issue by aliasgari-ka** [hossinasaadi/x-ui#152]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

با سلام خسته نباشید
چطور میتونم یوزر های یک سرور رو به سرور دیگر انتقال بدم ممنون میشم راهنمایی بفرمایید

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by alirezax5** [comment]
سلام اول داخل سرور دوم برنامه رو نصب کنید و دستور x-ui stop رو بفرستید
بعد داخل سرور اول از مسیر /etc/x-ui دیتابیس رو دانلود کن داخل سرور دوم بریز در آخر هم x-ui start بزن.

**Comment by AliM1988** [comment]
مسیر کامل فایل دیتابیس: 
/etc/x-ui/x-ui.db

با کمک ابزار های SFTP (مثل Filezilla)) میتونی بکاپ بگیری و توی سرور مجددا آپلود کنی

**Comment by aliasgari-ka** [comment]
آپلود میکنم ولی یوزر ها منتقل نمیشه و بعضا هم باگ میخوره کلا پنل بالا نمیاد

**Comment by alieffe** [comment]
> آپلود میکنم ولی یوزر ها منتقل نمیشه و بعضا هم باگ میخوره کلا پنل بالا نمیاد

اگه ssl را فعال کرده باشی باید مجوزها را هم منتقل کنی سرور دومت. اگه نداری، یوزرهایی که tls یا xtls فعال دارن را باید حذف کنی و بعد دیتابیس را منتقل کنی سرور دوم
