### ISSUE TITLE
Set outbound and chain multiple xrays

### ISSUE THREAD

**Issue by mjafari98** [hossinasaadi/x-ui#17]
I want to chain multiple xrays with a bridge & upstream x-ui.
So you connect to the bridge one; the bridge one connects to the upstream one.

Cient < = > bridge < = > upstream < = > internet

I tried changing `xray configuration template` and adding another outbound in it. But it was not successful. Do you have any ideas?

**Comment by hossinasaadi** [comment]
Hi ,You should run x-ui on bridge and with outbound to simple v2ray on upstream.

**Comment by Heshmatkhah** [comment]
Can you provide a sample outbound configuration for x-ui?
I can't find anything for configuring this scenario

**Comment by hossinasaadi** [comment]
> Can you provide a sample outbound configuration for x-ui?
> I can't find anything for configuring this scenario

https://github.com/hossinasaadi/v2ray-docker-compose

**Comment by mjafari98** [comment]
> > Can you provide a sample outbound configuration for x-ui?
> > I can't find anything for configuring this scenario
> 
> https://github.com/hossinasaadi/v2ray-docker-compose

There is no x-ui client in bridge in this repo.
