### ISSUE TITLE
افزودن امکانات

### ISSUE THREAD

**Issue by ZarinNegah** [hossinasaadi/x-ui#19]
سلام
ممنون بابت تلاشهاتون

مهمترین مواردی که نیازه

۱- امکانات افزودن کلاینت جدا با پورت یکسان ، الان فقط میشه روی هر کلاینت چند ای دی مختلف ایجاد کرد
و کلاینت جدید روی پورت یکسان نمیشه ایجاد کرد

۲- امکان محدودیت تعداد کاربری و تعیین آن مانند تک کاربره و دو و بیشتر و نظارت بر اتصال بر اساس آی دی اتصال
( چون اگر بر اساس پورت باشد،روی کلاینت های با پورت یکسان مشکل ایجاد میشه )

۳- امکان بکاپ و ریستور از داخل پنل
۴- full api
جهت دریافت اطلاعات
ویرایش و ساخت کلاینت و حذف و این چیزا

**Comment by amihos** [comment]
Yeah, API can be very useful: to be able to add, remove, edit users via API. Is it possible?

**Comment by alirezax5** [comment]
این پورت یکسان میتونه خیلی کمک کنه

**Comment by ZarinNegah** [comment]
> این پورت یکسان میتونه خیلی کمک کنه

دقیقا،خیلی این مورد بکار میاد
فقط نمیدونم صاحب این صفحه ایرانی هست یا نه،ما فارسی مینویسیم
چون توجهی به پیام ها نکرده تا الان

ولی بنظر میرسهفبرنامه نویس توانمندی هستند و امیدوارم بتونن این سیستم رو بر اساس ایده ها،مخصوصا ایده هایی که من مطرح کردم،انجام بدن

البته اگر بصورت پروژه شخصی هم انجام میدن،من حاضر هستم در توانم هزینه ای بابت جبران زحماتشون پرداخت کنم

**Comment by a7one** [comment]
دوست عزیز ایشون دارن روی دو مورد اولی که ذکر کردین کار میکنن ... توی گیتهابشون پروژه هاش هست

**Comment by ZarinNegah** [comment]
> دوست عزیز ایشون دارن روی دو مورد اولی که ذکر کردین کار میکنن ... توی گیتهابشون پروژه هاش هست

خبری از پیشرفت تلاش های این دوستمون دارید؟

**Comment by hossinasaadi** [comment]
> 
@alirezax5 @ZarinNegah @a7one @amihos 
install the latest version 0.4.4 : 
- add Multi User for VMess,VLess
- Multi translations

 if it's useful to you give repo :star2:

**Comment by alirezax5** [comment]
> > 
> 
> @alirezax5 @ZarinNegah @a7one @amihos install the latest version 0.4.4 :
> 
> * add Multi User for VMess,VLess
> * Multi translations
> 
> if it's useful to you give repo 🌟

Thanks, I tested it and it works well

but one thing!

The expiration date and total flow are applied to all clients, it would be great if the expiration date and total flow could be recorded for each email.

ممنون , آزمایش کردم به خوبی کار میکنه , اما یک نکته !

تاریخ انقضا و total flow برای تمام کلاینت ها اعمال میشه, اگه به ازای هر ایمیل بشه تاریخ انقضا و  total flow ثبت کرد خیلی خوب میشه.

**Comment by ZarinNegah** [comment]
> > 
> 
> @alirezax5 @ZarinNegah @a7one @amihos install the latest version 0.4.4 :
> 
> * add Multi User for VMess,VLess
> * Multi translations
> 
> if it's useful to you give repo 🌟

سلام
متشکرم بابت زحماتی که میکشید
ایده های زیادی برای ارتقا این سورس تو ذهنم دارم
مهمترین هاش 4 موردی هست که در ابتدا ذکر کردم
فرصت نمودید این 4 مورد را بررسی نمایید و آیا امکان کار بر روشون و افزودن به سورس شما می باشد؟
بازم ممنون

**Comment by Argo160** [comment]
> 

Great job and thanks.
i'm sure it is going to be the leading version of x-ui soon.
it is already perfect. but here is an idea which could be applied if you find it possible.
As a parental control i give my children like 500Mb daily access.
So everyday i reset their traffic manually. is it possible to set a time in the panel to reset the traffic usage automatically?
based on the server's time would be fine.

**Comment by hossinasaadi** [comment]
> ZarinNegah

contact TG : '@hexachan'

**Comment by hossinasaadi** [comment]
> NEW RELEASE ERROR: modify settingfail: xray template config invalid: invalid character '}' looking for beginning of object key @amirooo70 
add :
```  
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },

```

**Comment by hossinasaadi** [comment]
Almost all features added. So i close issue
