### ISSUE TITLE
merge english translation to you own brancg

### ISSUE THREAD

**Issue by alireza95jalili** [hossinasaadi/x-ui#24]
Hi, [this is a merge request](https://github.com/vaxilu/x-ui/pull/177) asked by @Msameim181 can you merge with your own fork?

[there is also a fork](https://github.com/FranzKafkaYu/x-ui) from @FranzKafkaYu that added English translation + telegram bot support and is very active.

**Comment by Msameim181** [comment]
Didn't he add Translation on this Fork? It seems he went further than Just a Translation.
But If he manages to connect it to TelegramBot That would be a major improvement.

I suggest that you (@hossinasaadi) contact GitHub Support and ask them to change this repo (from a forked repo) to a Normal repo.
If you need any help, contact me.
Be Safe.

**Comment by hossinasaadi** [comment]
Hi @Msameim181 , thanks for your suggestion :heart: 
acually we need to translate bash files.
feel free to contribute :+1: 
ty

**Comment by Msameim181** [comment]
Just bash files? Please specify the files and I will send a pull request.

**Comment by hossinasaadi** [comment]
yes, almost all the files are being translated!
could we have 2 langs when installing with bash?
[x-ui.sh](https://github.com/hossinasaadi/x-ui/blob/main/x-ui.sh) , [install.sh](https://github.com/hossinasaadi/x-ui/blob/main/install.sh)

**Comment by Msameim181** [comment]
We Can Have Two Different bashes, one for each language.

**Comment by hossinasaadi** [comment]
> We Can Have Two Different bashes, one for each language.

I think if we add a step in installation and ask the user language to be better. with 2 different arrays lang. is it possible?

**Comment by Msameim181** [comment]
It would be a bit messy. I suggest that you have a structure like this:
Directories: 
- scripts
     - installation
        - en
            - scripts.sh
        - zh-CN
            - scripts.sh
        - etc.

run.sh -> choose languages
install.sh -> choose languages



But there is a way that you could build based on languages.

**Comment by hossinasaadi** [comment]
> It would be a bit messy. I suggest that you have a structure like this: Directories:
> 
> * scripts
>   
>   * installation
>     
>     * en
>       
>       * scripts.sh
>     * zh-CN
>       
>       * scripts.sh
>     * etc.
> 
> run.sh -> choose languages install.sh -> choose languages
> 
> But there is a way that you could build based on languages.
so I suggest doing the installation just in English. the way you say it's too complicated.

**Comment by alireza95jalili** [comment]
@hossinasaadi  [this branch ](https://github.com/FranzKafkaYu/x-ui) already provided an English bash installer. why you wanna do it again? 
the panel is also translated into English.  you only need to merge your own new improvement for IP limitation.

**Comment by hossinasaadi** [comment]
Hi, this branch is private and you just install binary code exported from a
private repo. It’s a little scary :/

**Comment by alireza95jalili** [comment]
hmmmm.. This was a reasonable reason . you're right.
