### ISSUE TITLE
cant select xtls option in vless

### ISSUE THREAD

**Issue by surbiks** [hossinasaadi/x-ui#31]
hi
in the inbound setting cant select `xtls` config. if you select VLESS and want to config xTLS, after clicking on `xtls` check box all components in the inbound dialog do not work and need to refresh the page.

**Comment by hossinasaadi** [comment]
> > hi in the inbound setting cant select `xtls` config. if you select VLESS and want to config xTLS, after clicking on `xtls` check box all components in the inbound dialog do not work and need to refresh the page.
> 
> Hi @surbiks thanks for reporting. yes, it's occurred since the last PR.I fix it and in the next release, you can use it. maybe twonight

@surbiks 
install the lastest version 0.4.4. it fixed. if it's useful to you give repo star :star2:
