### ISSUE TITLE
Ip limit is not working

### ISSUE THREAD

**Issue by zeusking2004** [hossinasaadi/x-ui#38]
Hello my friend
Ip limit is not working 
Pls check it

**Comment by Argo160** [comment]
I use tunneling which means connecting to the vpn server via another server.
so everyone getting the same IP addresses and that causes the ip limit not working anymore!

**Comment by hossinasaadi** [comment]
> I use tunneling which means connecting to the vpn server via another server.
> so everyone getting the same IP addresses and that causes the ip limit not working anymore!

You should run x-ui on bridge server

**Comment by hossinasaadi** [comment]
> Hello my friend
> Ip limit is not working
> Pls check it

Read 10 last comment https://github.com/hossinasaadi/x-ui/issues/8

**Comment by Argo160** [comment]
I do not mean your IP limit restriction doesn't work.
It works perfectly if and only if the user connects directly to the x-ui node.
but if there is an intermediate node between the user device and the x-ui node, the IP limit option can not be used.
which most of us using that intermediate node these days.
anyway thanks for your effort.
hope someone else could explain this matter better than me

**Comment by Argo160** [comment]
![Untitled-1](https://user-images.githubusercontent.com/116899376/201311523-8345af0b-b823-45dc-ae5c-77e4138e99ea.jpg)

This may help to show what do i mean by same IP while tunneling.
these IPs are not on the same wifi or any shared network. they are on different cities!

**Comment by Argo160** [comment]
![Untitled-1](https://user-images.githubusercontent.com/116899376/201313661-4a4c5dc9-b905-4adc-9f66-3a1a851e819b.jpg)

same Ips at the same time while tunneling.
By the way They are not on the same network.
Hope it helps to understand the issue

**Comment by hossinasaadi** [comment]
Are you use duplicate email?

**Comment by Argo160** [comment]
Well
regarding to your question as duplicate email, it Seems you didn't read my previous comments.
do you want me to explain it in Persian?

**Comment by malikshi** [comment]
> which most of us using that intermediate node these days.

do you mean over cdn or like relay tunnel?

**Comment by Argo160** [comment]
> > which most of us using that intermediate node these days.
> 
> do you mean over cdn or like relay tunnel?

It has nothing to do with the cdn.
it is so simple
just imagine you are using two vps
the user connects to the first vps which its job is only forwarding the packets to the second vps.
the first vps has nothing to do anything with any protocols. just simple forwarding to the second vps.
so all the time the second vps receives the packets with the same IP which is the first vps ip.
 
All i am asking is: 
if it is possible we use something more unique than ip. something like mac address or device id or device name... to restrict the connection

**Comment by zarvan9** [comment]
من فارسی مینویسم همه بفهمین، بنده خدا خودشو پاره کرد.
 منظورش اینه وقتی ی سرور از ایران تانل میشه به سرور خارج محدودیت ایپی کار نمیکنه چون هرچقدر ادم متصل بشه  ایپی سرور ایران به جای ایپی اصلی کاربر روی اسکریپت میفته.
 فعلا از روش ریورس پروکسی استفاده کن @Argo160 
 https://telegra.ph/reverse-proxy-on-nginx-for-x-ui-11-08
 و این کد کار خودشو انجام میده و ایپی اصلی کاربر رو میفرسته
 map $proxy_add_x_forwarded_for $client_ip {"~(?<IP>([0-9]{1,3}\.){3}[0-9]{1,3}),.*" $IP;}

**Comment by Argo160** [comment]
> من فارسی مینویسم همه بفهمین، بنده خدا خودشو پاره کرد. منظورش اینه وقتی ی سرور از ایران تانل میشه به سرور خارج محدودیت ایپی کار نمیکنه چون هرچقدر ادم متصل بشه ایپی سرور ایران به جای ایپی اصلی کاربر روی اسکریپت میفته. فعلا از روش ریورس پروکسی استفاده کن @Argo160 https://telegra.ph/reverse-proxy-on-nginx-for-x-ui-11-08 و این کد کار خودشو انجام میده و ایپی اصلی کاربر رو میفرسته map $proxy_add_x_forwarded_for $client_ip {"~(?([0-9]{1,3}.){3}[0-9]{1,3}),.*" $IP;}

ممنون دوست عزیز.
بالاخره یه نفر گرفت چی میگم :)
روش ریورس نیاز به هیچ کانفیگ خاصی در سرور ایران نداره؟ 
و حتما دامنه باید پراکسی شده باشه؟ یا ضروری نیست

**Comment by malikshi** [comment]
> Finally, someone got it, what am I saying :)
> The reverse method does not require any special configuration on the Iranian server?

I see what are you want to do.

> And must the domain be proxied? or not necessary

no need to proxied if you're need to use SNI(allowInsecure true).

**Comment by VISOHI** [comment]
hi . i install this new version but ip limit not disabled inbound

**Comment by Argo160** [comment]
> need to proxied if you're need to us

So you mean for having "Reverse Proxy", it doesn't need to be proxied?

**Comment by Argo160** [comment]
> hi . i install this new version but ip limit not disabled inbound

اگه مثل من از سرور ایران استفاده میکنی که بله کار نمیکنه.
اما اگه سرور ایران نداری آی پی لیمیت علی الظاهر به درستی کار میکنه

**Comment by a7one** [comment]
> > need to proxied if you're need to us
> 
> @malikshi So you mean for having "Reverse Proxy", the domain doesn't need to be proxied?

نه اجباری نیست به پروکسی کردن دامین

**Comment by VISOHI** [comment]
> > hi . i install this new version but ip limit not disabled inbound
> 
> اگه مثل من از سرور ایران استفاده میکنی که بله کار نمیکنه. اما اگه سرور ایران نداری آی پی لیمیت علی الظاهر به درستی کار میکنه

از سرور ایران استفاده نمیکنم اما کار نمیکنه بازم

**Comment by mory** [comment]
منم تایید میکنم، تست کردم کار نمیکنه، و اینکه وقتی تو نود رو ساختی بعدش تو قسمت ویرایش میری، اطلاعات ایمیل و ایپی خالیه.

**Comment by amink69** [comment]
Hi everyone
i had issue with this v2ray
after install panel
i get an error that show me can't load config
i saw in internet this is a bug
does anyone know how we can fix that ?

من با این نسخه مشکل دارم 
بعد نصب پنل یک خطا گرفتم که نوشته بود نمیتونه کانفیگ رو لود کنه
تو اینترنت نوشته بود باگه
ولی راهی پیدا نکردم
کسی میدونه باید چیکار کنیم ؟

**Comment by hossinasaadi** [comment]
> منم تایید میکنم، تست کردم کار نمیکنه، و اینکه وقتی نود رو ساختی بعدش تو قسمت ویرایش میری، اطلاعات ایمیل و ایپی خالیه. اوبنتو 22 دارم. vless+xtls کانفیگم بود

Hi @mory  read this steps. https://github.com/hossinasaadi/x-ui/blob/main/README.md#enable-ip-restrictions-per-inbound

**Comment by hossinasaadi** [comment]
> Hi everyone i had issue with this v2ray after install panel i get an error that show me can't load config i saw in internet this is a bug does anyone know how we can fix that ?
> 
> من با این نسخه مشکل دارم بعد نصب پنل یک خطا گرفتم که نوشته بود نمیتونه کانفیگ رو لود کنه تو اینترنت نوشته بود باگه ولی راهی پیدا نکردم کسی میدونه باید چیکار کنیم ؟

Hi, @amink69 enter this `x-ui status` command and send logs here to check it out.

**Comment by mory** [comment]
Hi @hossinasaadi

**Comment by hossinasaadi** [comment]
> Hi @hossinasaadi After adding logs code a core restart is needed i think but you did not mention it .. right?!

yes indeed.

**Comment by amink69** [comment]
hello
when users all connected to one Wifi Router they can use one limited account at the same time.

**Comment by mory** [comment]
Its still not working. why did you close it

**Comment by hossinasaadi** [comment]
> Its still not working. why did you close it

Hi @mory it works for all users, you may have wrong config or something, 
1- set ip server in inbound monitor ip
2- set ip limit to 1
3- add code to config
See it works 
Let me know if u can’t

**Comment by mory** [comment]
I don't have 2 separate IPs atm, I'll do a clean install and test precisely again tomorrow at work.

**Comment by hossinasaadi** [comment]
> 

look, this feature can't detect Devices! it Detects IPs. so if you wanna connect with 2 devices with the same IP, it not gonna work!

**Comment by mory** [comment]
i keeped watch on log file and i saw 2 ips logged sometimes, and it do drop one ip in seconds but the point is the secound connection has enough time to buffer video or load things and will do it again on its next success connect.
am i right ?!

**Comment by hossinasaadi** [comment]
> i keeped watch on log file and i saw 2 ips logged sometimes, and it do drop one ip in seconds but the point is the secound connection has enough time to buffer video or load things and will do it again on its next success connect. am i right ?!

yes, it prevents usage at the same time for one of IPs, So if one of them stops for about 30s and sends no packets, the other one can connect.

**Comment by mory** [comment]
im using desktop and my phone, but i have access to net almost in same time... i dont see any blocking :(
i assume i dont know how to config, feel free to close it since no one confirm the problem anymore

**Comment by nursemazloom** [comment]
> من فارسی مینویسم همه بفهمین، بنده خدا خودشو پاره کرد. منظورش اینه وقتی ی سرور از ایران تانل میشه به سرور خارج محدودیت ایپی کار نمیکنه چون هرچقدر ادم متصل بشه ایپی سرور ایران به جای ایپی اصلی کاربر روی اسکریپت میفته. فعلا از روش ریورس پروکسی استفاده کن @Argo160 https://telegra.ph/reverse-proxy-on-nginx-for-x-ui-11-08 و این کد کار خودشو انجام میده و ایپی اصلی کاربر رو میفرسته map $proxy_add_x_forwarded_for $client_ip {"~(?([0-9]{1,3}.){3}[0-9]{1,3}),.*" $IP;}

اینو یکم توضیح میدی باید nginx روی سرور ایران نصب بشه یا روی سروری که x-ui نصب شده؟
و این که توی کانفیگ بدون دامنه باید آی پی کدوم سرور وارد بشه یا کلا آی پی که خودش داده باشه؟

**Comment by Argo160** [comment]
> im using desktop and my phone, but i have access to net almost in same time... i dont see any blocking :( i assume i dont know how to config, feel free to close it since no one confirm the problem anymore

Just for your info many of my friends got the same problem. it doesn't matter whether you get confirmation or not, the issue will be closed.
i just found a solution to my issue and came here to write it down here (which could be helpful to others) but surprisingly my issue was gone! lol

**Comment by hossinasaadi** [comment]
> im using desktop and my phone, but i have access to net almost in same time... i dont see any blocking :( i assume i dont know how to config, feel free to close it since no one confirm the problem anymore

which config you use for inbound?

**Comment by mory** [comment]
My config is :
[![H9Qd0t1.md.jpg](https://iili.io/H9Qd0t1.md.jpg)](https://freeimage.host/i/H9Qd0t1)

**Comment by hossinasaadi** [comment]
Enter server ip in Listen Ip field and check it.

**Comment by nursemazloom** [comment]
> > من فارسی مینویسم همه بفهمین، بنده خدا خودشو پاره کرد. منظورش اینه وقتی ی سرور از ایران تانل میشه به سرور خارج محدودیت ایپی کار نمیکنه چون هرچقدر ادم متصل بشه ایپی سرور ایران به جای ایپی اصلی کاربر روی اسکریپت میفته. فعلا از روش ریورس پروکسی استفاده کن @Argo160 https://telegra.ph/reverse-proxy-on-nginx-for-x-ui-11-08 و این کد کار خودشو انجام میده و ایپی اصلی کاربر رو میفرسته map $proxy_add_x_forwarded_for $client_ip {"~(?([0-9]{1,3}.){3}[0-9]{1,3}),.*" $IP;}
> 
> ممنون دوست عزیز. بالاخره یه نفر گرفت چی میگم :) روش ریورس نیاز به هیچ کانفیگ خاصی در سرور ایران نداره؟ و حتما دامنه باید پراکسی شده باشه؟ یا ضروری نیست

سلام شما تونستید ریورس پروکسی رو راه اندازی کنید؟
اگه این کارو انجام دادین میشه بگین چیکار کردین من هر کاری میکنم نمیشه:(

**Comment by mory** [comment]
@hossinasaadi 
It works now but tls needs domain name if i enter ip it wont deliver correct settings to client and should edit manually which is not good. Thank you btw

**Comment by Argo160** [comment]
> 
> سلام شما تونستید ریورس پروکسی رو راه اندازی کنید؟ اگه این کارو انجام دادین میشه بگین چیکار کردین من هر کاری میکنم نمیشه:(

نه متاسفانه.
خسته‌م کرد بیخیالش شدم کلا.
با همون روش NapsternetV دارم کار میکنم.

**Comment by hossinasaadi** [comment]
> @hossinasaadi It works now but xtls needs domain name if i enter ip it wont deliver correct settings to the client and should edit manually which is not good. Thank you btw

look when enter Listen IP and generate QR,replace your Domain with the IP in QR code Output and check it out!

**Comment by mory** [comment]
it may work but its still not the proper way .. this issue now can be closed but another issue should be opened to fix it in a proper way.

**Comment by nursemazloom** [comment]
> > سلام شما تونستید ریورس پروکسی رو راه اندازی کنید؟ اگه این کارو انجام دادین میشه بگین چیکار کردین من هر کاری میکنم نمیشه:(
> 
> نه متاسفانه. خسته‌م کرد بیخیالش شدم کلا. با همون روش NapsternetV دارم کار میکنم.

منم خسته کرده همه یه چیزی میگن ولی هیچ کس نمیاد یه توضیح واضح بهمون بده

**Comment by nursemazloom** [comment]
> > @hossinasaadi It works now but xtls needs domain name if i enter ip it wont deliver correct settings to the client and should edit manually which is not good. Thank you btw
> 
> look when enter Listen IP and generate QR,replace your Domain with the IP in QR code Output and check it out!

مستر اسدی شما نمیتونید یه راه حلی برای تونل سرور ایران درست کنید تا بشه ما هم از این برنامه استفاده کنیم

**Comment by hossinasaadi** [comment]
@nursemazloom https://github.com/hossinasaadi/x-ui/issues/118

**Comment by erfanslr** [comment]
> My config is : [![H9Qd0t1.md.jpg](https://camo.githubusercontent.com/f4cefda3f7687cc400f19e1d8a4f290dce7c96a3d92bbc9ba7972bc755dd671d/68747470733a2f2f69696c692e696f2f483951643074312e6d642e6a7067)](https://freeimage.host/i/H9Qd0t1)

سلام چجوری تو پنل xui محدودیت ip بذارم برای هر کانکشن؟
