### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by alpha856** [hossinasaadi/x-ui#49]
Hi, I have some suggestions to improve this product.

a. Limit inbound connections or devices with IPtables on Ports or other methods. IPtables (or like methods) works better in networks with NAT technology and also be usable for separate between device and  NAT connection.

b. add saved cert path options in web panel settings and also add selectable menu to import SSL certs in config generation.

**Comment by hossinasaadi** [comment]
Hi @alpha856, it's not possible right now.thanks for suggestion
