### ISSUE TITLE
Problem adding inbounds

### ISSUE THREAD

**Issue by alirezax5** [hossinasaadi/x-ui#53]
Hello, when you press the + button, the modal does not open, and the following error is written in the console saying that **this.inbound.isExpiry** is not a function.

![photo_2022-11-15_18-03-12](https://user-images.githubusercontent.com/20362833/201947036-dbe2a1ae-cf23-4be6-9d4b-4a65dbeeb68b.jpg)

**Comment by hossinasaadi** [comment]
@alirezax5  clear browser cache and let me know

**Comment by alirezax5** [comment]
> @alirezax5 clear browser cache and let me know

The problem was solved,tnx
