### ISSUE TITLE
problem with docker of Chasing66

### ISSUE THREAD

**Issue by se8820726** [hossinasaadi/x-ui#55]
hi

I absolutely must use docker type of your v2ray

where is config file in docker provided by Chasing66 ?

I dont see 'email' and 'ip count limit' when creating vmess and vless in docker  provided by Chasing66

**Comment by hossinasaadi** [comment]
Hi @se8820726 i don’t update docker file but i do it as soon as possible

**Comment by hossinasaadi** [comment]
I close issue, if your problem isn’t solved let me know here
