### ISSUE TITLE
error Extracting master.tar.gz

### ISSUE THREAD

**Issue by NoRRt** [hossinasaadi/x-ui#59]
[Wed 16 Nov 2022 10:29:22 PM CET] Extracting master.tar.gz
[Wed 16 Nov 2022 10:29:22 PM CET] It is recommended to install socat first.
[Wed 16 Nov 2022 10:29:22 PM CET] We use socat for standalone server if you use standalone mode.
[Wed 16 Nov 2022 10:29:22 PM CET] If you don't use standalone mode, just ignore this warning.

![Untitled](https://user-images.githubusercontent.com/4822035/202299330-01013899-d281-496a-bf3b-46351b8cd612.jpg)

**Comment by nshayanfar** [comment]
Acme (and its installation) is not directly related to this repository. Please ask your question in its suitable place.
