### ISSUE TITLE
Panel not aaccessible after update

### ISSUE THREAD

**Issue by Argo160** [hossinasaadi/x-ui#60]
After the latest update, the panel is not accessible anymore.
i tried to reboot the x-ui via ssh but no luck here is what it shows:

> Panel state: Not Running
> Start automatically: Yes
> xray state: Not Running
> Warning: The unit file, source configuration file or drop-ins of x-ui.service changed on disk. Run 'systemctl daemon-reload' to reload units.
> [ERR] Panel restart failed，Probably because it takes longer than two seconds to start，Please check the log information later

**Comment by nshayanfar** [comment]
Have you tried daemon-reload?

**Comment by hossinasaadi** [comment]
> After the latest update, the panel is not accessible anymore. i tried to reboot the x-ui via ssh but no luck here is what it shows:
> 
> > Panel state: Not Running
> > Start automatically: Yes
> > xray state: Not Running
> > Warning: The unit file, source configuration file or drop-ins of x-ui.service changed on disk. Run 'systemctl daemon-reload' to reload units.
> > [ERR] Panel restart failed，Probably because it takes longer than two seconds to start，Please check the log information later

send output of : x-ui status 
and also I check new version and it installs without problem

**Comment by hossinasaadi** [comment]
> After the latest update, the panel is not accessible anymore. i tried to reboot the x-ui via ssh but no luck here is what it shows:
> 
> > Panel state: Not Running
> > Start automatically: Yes
> > xray state: Not Running
> > Warning: The unit file, source configuration file or drop-ins of x-ui.service changed on disk. Run 'systemctl daemon-reload' to reload units.
> > [ERR] Panel restart failed，Probably because it takes longer than two seconds to start，Please check the log information later

send output of : x-ui status 
and also I check new version and it installs without problem
