### ISSUE TITLE
x-ui in terminal

### ISSUE THREAD

**Issue by HunterBax** [hossinasaadi/x-ui#64]
The x-ui command does not open in the terminal
![image](https://user-images.githubusercontent.com/38705799/202442607-0abed07e-26ef-4799-b181-80441aac381e.png)

**Comment by hossinasaadi** [comment]
https://github.com/hossinasaadi/x-ui#install--upgrade
`bash <(curl -Ls https://raw.githubusercontent.com/hossinasaadi/x-ui/master/install.sh)
`
