### ISSUE TITLE
آی پی لیمیت

### ISSUE THREAD

**Issue by DanialSaebi** [hossinasaadi/x-ui#65]
خیلی ممنون از کار زیبای شما

اگر بخوایم یه کد دو تا دیوایس وصل بشن و موقع چنج کردن اینترنت دستگاه به مشکل نخورن چه عددی رو توی ای پی لیمیت قرار بدیم؟

اگر یه توضیحات کلی هم بدین در مورد ای پی لیمیت ممنون میشم

**Comment by hossinasaadi** [comment]
Hi @DanialSaebi, each 10s IP log for each user will clear. but for more flexibility, you can set the IP limit to 3

**Comment by DanialSaebi** [comment]
Thank you @hossinasaadi
