### ISSUE TITLE
[BUG] Show wrong traffic usage

### ISSUE THREAD

**Issue by shynm** [hossinasaadi/x-ui#66]
Hello sir.

Panel show wrong traffic usage in modify InBounds But show correct in InBounds.

![qqq](https://user-images.githubusercontent.com/17863406/202478283-83af213b-a3b4-48cf-a521-818fecc01a89.jpg)

**Comment by hossinasaadi** [comment]
If the description that I told wasn’t clear let me know. So I close issue

**Comment by shynm** [comment]
Thanks For reply @hossinasaadi .
In this Inbound I have one User.
It's Show wrong usage.

**Comment by Recoba86** [comment]
> Thanks For reply @hossinasaadi . In this Inbound I have one User. It's Show wrong usage.

reset both traffic now and test it again!

**Comment by Jolge100** [comment]
i have this problem too and reset both traffic but didnt work
