### ISSUE TITLE
Switch version doesn't work

### ISSUE THREAD

**Issue by ITheEqualizer** [hossinasaadi/x-ui#74]
When you switch to version 1.6.5 it shows the success message but once you refresh the panel it is still on 1.6.4 and it doen't change.

**Comment by hossinasaadi** [comment]
please read this : https://github.com/hossinasaadi/x-ui/issues/50

**Comment by ITheEqualizer** [comment]
Still not working.

**Comment by hossinasaadi** [comment]
> Still not working.

bro the latest xray core is 1.6.4 and we are use customized version as 1.6.5 but when you installed it will appear as 1.6.4

**Comment by ITheEqualizer** [comment]
Oh, my bad.
