### ISSUE TITLE
Update without losing the database

### ISSUE THREAD

**Issue by Ariojavand** [hossinasaadi/x-ui#75]
hi , tnx for adding these features
Is there any way to upgrade the [vaxil ](https://github.com/vaxilu/x-ui)version to this version without losing the database?

And after installing this version, if a new update is released, what command should be used to update it?

**Comment by hossinasaadi** [comment]
Hi @Ariojavand, there is no data loss at the update to this version but you can get a backup from your current database in `/etc/x-ui/x-ui.db`
