### ISSUE TITLE
اتصال دیتابیس های v2 در چند سرور

### ISSUE THREAD

**Issue by bestkilleriranlod** [hossinasaadi/x-ui#76]
سلام
من میخوام چند سرور v2 به هم متصل کنم تا همه یک دیتابیس داشته باشن
راهکاری برای اینکار دارید؟
و اینکه اگر قابلیتی اضافه بشه به api که ترافیک مصرفی کاربر هم بشه اپدیت کرد خیلی عالی میشه برای این مسئله

**Comment by hossinasaadi** [comment]
it needs a different platform to do that.
and API may update in the next version.
