### ISSUE TITLE
تانل کردن بین دو سرور

### ISSUE THREAD

**Issue by XemonDev** [hossinasaadi/x-ui#78]
با سلام
برای تانل کردن بین دو سرور که x-ui نصب دارن باید چیکار کنیم؟
خیلی از دیتاسنتر هایی که سرور های ایران ارائه میدن فورواردینگ پورت رو بستن

**Comment by IamYousef** [comment]
shomma mitoonid az in dastoorat:
```
sysctl net.ipv4.ip_forward=1
iptables -t nat -A PREROUTING -p tcp --dport 22 -j DNAT --to-destination IRAN_IP
iptables -t nat -A PREROUTING -j DNAT --to-destination EU_IP
iptables -t nat -A POSTROUTING -j MASQUERADE
```
estefade konid, ya
roo server iran ham x-ui berizid va az confige `dokodemo-door` estefade konid
rahe 2vom behtare

**Comment by XemonDev** [comment]
راه اول که گفتم فوروارد رو بستن نمیشه فوروارد کرد
راه دوم هم میتونید بیشتر راجع بهش توضیح بدید؟

**Comment by XemonDev** [comment]
> > راه اول که گفتم فوروارد رو بستن نمیشه فوروارد کرد راه دوم هم میتونید بیشتر راجع بهش توضیح بدید؟
> 
> https://www.v2fly.org/en_US/config/protocols/dokodemo.html#transparent-proxy-configuration-example

نمونه ای دارید شما؟
چون تخصصی ندارم نتیجه ی مفیدی پیدا نکردم

**Comment by surbiks** [comment]
xray and v2ray support multi-chain proxy. if you use Iran VPS as a bridge to connect outside VPS need to create an outbound to outside VPS from the Iran server.

clien -------> bridge -------> outside -------> internet

1- in outside VPS run Xray or v2ray with inbound Vless or VMess
2- in bridge VPS define outbound to connect outside VPS
3- in bridge VPS define inbound for clients
4- in bridge VPS define a rule to send client inbound to outside VPS outbound

X-UI project need some change to support this but you can use tun2socks in the bridge 

1- in outside VPS run Xray or v2ray with inbound Vless or VMess
2- in bridge VPS run Xray and connect to outside as client (define socks5 inbound to send traffic)
3- run tun2socks and send all bridge traffic to socks5 (this socks5 send traffic to outside)
4- run X-UI and define clients

**Comment by IamYousef** [comment]
> راه اول که گفتم فوروارد رو بستن نمیشه فوروارد کرد
> راه دوم هم میتونید بیشتر راجع بهش توضیح بدید؟

اگر سرور رو از پارس وی دی اس (parsvds) تهیه کنید به این مشکل بر نمیخورید

داخل پنل x-ui بشید از سرور ایرانتون، یک کانفیگ dokodomo-door درست کنید که ip مقصد سرور خارج و پورت هم برابر با پورت کانفیگ مورد نظرتون که داخل سرور خارج درست کردید قرار میدید. 
کانفیگ سرور خارج رو کپی میکنید، و به جای ip و پورتی که بهتون میده، شما ip و پورت سرور ایران با  کانفیگ dokomodoor قرار میدید. حالا شما بر فرض مثال وصل میشید به iranip:32459 که تمام اطلاعات رو bridge‌ میکنه به noniran:vmess_port.
تادا شما حالا ۲ تا سرور به بریج کردید بدون افت کیفیت یا سرعت. ولی از اونجایی که برای هر کانفیگ خارج یه کانفیگم تو ایرا باید درست کنید، ممکنه کارتون سخت شه. 
برا راحتی یا سرور رو عوض کنید که پورت forwarding باز باشه و از tun2socks یا دستوری که بالاتر قرار دادم استفاده کنید.
همچنین پروتوکال dokomodoor باز هست و اطلاعات بین شما و سرور ایران رمز گذاری نمیشه و اگر یکی بخواد لاگ بگیره از سرور ایران حدودا میشه گفت میتونن تمام ترافیکتون رو ببینن که غیر قانونیه ولی چون تو ایرانی قانونیه 😁

**Comment by Recoba86** [comment]
> > راه اول که گفتم فوروارد رو بستن نمیشه فوروارد کرد
> > راه دوم هم میتونید بیشتر راجع بهش توضیح بدید؟
> 
> اگر سرور رو از پارس وی دی اس (parsvds) تهیه کنید به این مشکل بر نمیخورید
> 
> داخل پنل x-ui بشید از سرور ایرانتون، یک کانفیگ dokodomo-door درست کنید که ip مقصد سرور خارج و پورت هم برابر با پورت کانفیگ مورد نظرتون که داخل سرور خارج درست کردید قرار میدید. کانفیگ سرور خارج رو کپی میکنید، و به جای ip و پورتی که بهتون میده، شما ip و پورت سرور ایران با کانفیگ dokomodoor قرار میدید. حالا شما بر فرض مثال وصل میشید به iranip:32459 که تمام اطلاعات رو bridge‌ میکنه به noniran:vmess_port. تادا شما حالا ۲ تا سرور به بریج کردید بدون افت کیفیت یا سرعت. ولی از اونجایی که برای هر کانفیگ خارج یه کانفیگم تو ایرا باید درست کنید، ممکنه کارتون سخت شه. برا راحتی یا سرور رو عوض کنید که پورت forwarding باز باشه و از tun2socks یا دستوری که بالاتر قرار دادم استفاده کنید. همچنین پروتوکال dokomodoor باز هست و اطلاعات بین شما و سرور ایران رمز گذاری نمیشه و اگر یکی بخواد لاگ بگیره از سرور ایران حدودا میشه گفت میتونن تمام ترافیکتون رو ببینن که غیر قانونیه ولی چون تو ایرانی قانونیه 😁

یعنی از این پارس وی دی اس که گفتید اگه وی پی اس بگیریم
با همین دستور

`sysctl net.ipv4.ip_forward=1
iptables -t nat -A PREROUTING -p tcp --dport 22 -j DNAT --to-destination IRAN_IP
iptables -t nat -A PREROUTING -j DNAT --to-destination EU_IP
iptables -t nat -A POSTROUTING -j MASQUERADE`

سرور ایران رو میشه تونل کرد؟
. فقط لازم هست یک ux-i روی سرور ایران داشته باشیم
درسته؟!

**Comment by XemonDev** [comment]
> > راه اول که گفتم فوروارد رو بستن نمیشه فوروارد کرد
> > راه دوم هم میتونید بیشتر راجع بهش توضیح بدید؟
> 
> اگر سرور رو از پارس وی دی اس (parsvds) تهیه کنید به این مشکل بر نمیخورید
> 
> داخل پنل x-ui بشید از سرور ایرانتون، یک کانفیگ dokodomo-door درست کنید که ip مقصد سرور خارج و پورت هم برابر با پورت کانفیگ مورد نظرتون که داخل سرور خارج درست کردید قرار میدید. کانفیگ سرور خارج رو کپی میکنید، و به جای ip و پورتی که بهتون میده، شما ip و پورت سرور ایران با کانفیگ dokomodoor قرار میدید. حالا شما بر فرض مثال وصل میشید به iranip:32459 که تمام اطلاعات رو bridge‌ میکنه به noniran:vmess_port. تادا شما حالا ۲ تا سرور به بریج کردید بدون افت کیفیت یا سرعت. ولی از اونجایی که برای هر کانفیگ خارج یه کانفیگم تو ایرا باید درست کنید، ممکنه کارتون سخت شه. برا راحتی یا سرور رو عوض کنید که پورت forwarding باز باشه و از tun2socks یا دستوری که بالاتر قرار دادم استفاده کنید. همچنین پروتوکال dokomodoor باز هست و اطلاعات بین شما و سرور ایران رمز گذاری نمیشه و اگر یکی بخواد لاگ بگیره از سرور ایران حدودا میشه گفت میتونن تمام ترافیکتون رو ببینن که غیر قانونیه ولی چون تو ایرانی قانونیه 😁

ممنونم از توضیحات خوبتون
یعنی اینکه هر کاری رو یوزر ها انجام میدن مشخص میشه؟
و اینکه چرا چون تو ایرانیم قانونیه متوجه این عرض نشدم

بعدم اینکه فکرکنم سرور های پارس وی دی اس محدودیت یک به ده داشته باشه

**Comment by hossinasaadi** [comment]
it's not an issue please open discussion for this talk, ty
