### ISSUE TITLE
wrong qr generate in multi user

### ISSUE THREAD

**Issue by MrMohebi** [hossinasaadi/x-ui#79]
when put project behind nginx RP the URL in generated qr will be same as x-ui domain not as "domain name" specified in xtls

**Comment by hossinasaadi** [comment]
Hi @MrMohebi can you say that more clearly? may send a shot or something.

**Comment by MrMohebi** [comment]
I use ```a.domain.com``` for my panel and ```b.domain.com``` for VLESS/XTLS "domain name" when I generated QR code it use ```a.domain.com``` insted of ```b.domain.com```
![image](https://user-images.githubusercontent.com/30952565/202846631-e198361b-7ebd-4f99-bec5-5b90bf34d04f.png)
![image](https://user-images.githubusercontent.com/30952565/202846634-d36929d5-92f1-4927-b1b8-04fdabdd9f77.png)

**Comment by hossinasaadi** [comment]
i see, let me check it

**Comment by hossinasaadi** [comment]
fixed in the new version, thanks for reporting @MrMohebi
