### ISSUE TITLE
IP limit doesn't work.

### ISSUE THREAD

**Issue by Artin70** [hossinasaadi/x-ui#8]
I tested the IP limit by connecting with laptop (wifi) and phone (data) at the same time. 2 different IPs are shown in IP Log but both devices are connected without any limit. Tested with xray 1.4.0 and the last version (1.6.2).
![ip limit-1](https://user-images.githubusercontent.com/117419970/200075794-25fa8a2b-1896-4a32-9e38-526899ace987.jpg)

**Comment by hossinasaadi** [comment]
are u able to change to TCP ?

**Comment by hossinasaadi** [comment]
> I tested the IP limit by connecting with laptop (wifi) and phone (data) at the same time. 2 different IPs are shown in IP Log but both devices are connected without any limit. Tested with xray 1.4.0 and the last version (1.6.2). ![ip limit-1](https://user-images.githubusercontent.com/117419970/200075794-25fa8a2b-1896-4a32-9e38-526899ace987.jpg)

if TCP doesn't solve your problem,set your ip server in Listen IP

**Comment by rezatitan7** [comment]
I can confirm that, the one before this one worked, but this new updated version does not limit anything.
How can I get the older version back, as I need it very badly

**Comment by Artin70** [comment]
> > I tested the IP limit by connecting with laptop (wifi) and phone (data) at the same time. 2 different IPs are shown in IP Log but both devices are connected without any limit. Tested with xray 1.4.0 and the last version (1.6.2). ![ip limit-1](https://user-images.githubusercontent.com/117419970/200075794-25fa8a2b-1896-4a32-9e38-526899ace987.jpg)
> 
> if TCP doesn't solve your problem,set your ip server in Listen IP

I changed WS to TCP, same result. Then, as you said, **I assigned the Server IP to Listen IP. It seems to be working** independently of transmision type (WS or TCP) and Xray version.
As I noticed, the limiting process works as this: first the second IP connects and both IPs works properly, and after 2-3 min, one of them connect-reconnect for like 10 sec, then one disconnects and after that both connect for several seconds again and this process repeats itself. So the limitation works as a connectivity disruption.

**Comment by hossinasaadi** [comment]
> > >
> I changed WS to TCP, same result. Then, as you said, **I assigned the Server IP to Listen IP. It seems to be working** independently of transmision type (WS or TCP) and Xray version. As I noticed, the limiting process works as this: first the second IP connects and both IPs works properly, and after 2-3 min, one of them connect-reconnect for like 10 sec, then one disconnects and after that both connect for several seconds again and this process repeats itself. So the limitation works as a connectivity disruption.

Hi @Artin70 , thank you for reporting this issue. please install the new version and let me know :heart:

**Comment by conall1995** [comment]
i have this problem too

thanks you for working on it :)

**Comment by hossinasaadi** [comment]
> i have this problem too
> 
> thanks you for working on it :)

do you install the new version? still have problem?

**Comment by conall1995** [comment]
yes 
installed right now and not work 
![Screen Shot 1401-08-14 at 15 15 44](https://user-images.githubusercontent.com/28934905/200118361-25491877-b0ae-478b-9be5-99c6997d1a0e.png)

**Comment by hossinasaadi** [comment]
set ws to tcp and check it out

**Comment by hossinasaadi** [comment]
set ws to tcp and check it out
and also use 1.4.0 version! @conall1995 @rezatitan7

**Comment by conall1995** [comment]
> set ws to tcp and check it out

set tcp -> x-ui not working error code 503 -> change to ws (with db file) -> work again

**Comment by rezatitan7** [comment]
> set ws to tcp and check it out and also use 1.4.0 version! @conall1995 @rezatitan7

@hossinasaadi Still no avail.

**Comment by rezatitan7** [comment]
![Annotation 2022-11-05 155047](https://user-images.githubusercontent.com/61632298/200119932-25b76649-726f-410e-894c-ebc4e321c4b9.png)
![Annotation 2022-11-05 155716](https://user-images.githubusercontent.com/61632298/200119935-51c5bc68-b865-481b-ad46-81e987fe55b9.png)

**Comment by rezatitan7** [comment]
It used to work on VMess+WS/TCP

**Comment by hossinasaadi** [comment]
> It used to work on VMess+WS/TCP
@rezatitan7 
contact in tg : `@hexachan`

**Comment by Dovlet241** [comment]
Hi
i t doesn't work for me either, i updated a few minutes ago

**Comment by Artin70** [comment]
> > > >
> > 
> > 
> > I changed WS to TCP, same result. Then, as you said, **I assigned the Server IP to Listen IP. It seems to be working** independently of transmision type (WS or TCP) and Xray version. As I noticed, the limiting process works as this: first the second IP connects and both IPs works properly, and after 2-3 min, one of them connect-reconnect for like 10 sec, then one disconnects and after that both connect for several seconds again and this process repeats itself. So the limitation works as a connectivity disruption.
> 
> Hi @Artin70 , thank you for reporting this issue. please install the new version and let me know ❤️

Just tested the new release (3.9.1) with xray 1.4.0, TCP and WS, with using Listen IP and without using it. It doesn't work properly but only when I use Listen IP, the connection on the first device disconnects almost every 3 min and it gets connected after a few seconds. the last release (3.8.0) seemed to work better as I mentioned in my last comment.

**Comment by hossinasaadi** [comment]
> > > > >
> > > 
> > > 
> > > I changed WS to TCP, same result. Then, as you said, **I assigned the Server IP to Listen IP. It seems to be working** independently of transmision type (WS or TCP) and Xray version. As I noticed, the limiting process works as this: first the second IP connects and both IPs works properly, and after 2-3 min, one of them connect-reconnect for like 10 sec, then one disconnects and after that both connect for several seconds again and this process repeats itself. So the limitation works as a connectivity disruption.
> > 
> > 
> > Hi @Artin70 , thank you for reporting this issue. please install the new version and let me know heart
> 
> Just tested the new release (3.9.1) with xray 1.4.0, TCP and WS, with using Listen IP and without using it. It doesn't work properly but only when I use Listen IP, the connection on the first device disconnects almost every 3 min and it gets connected after a few seconds. the last release (3.8.0) seemed to work better as I mentioned in my last comment.

@Dovlet241 @Artin70 
use `sudo x-ui update`  to get new version 0.3.9.2

**Comment by Dovlet241** [comment]
version 0.3.9.2 is not working too.
in first release of this script when for first time Vless implanted, i was using Vless with WS and Xray core was 1.6.1 and 1.6.0 and everything worked fine. i don't think it is relevant to using TCP or Xcore 1.4.0 to work.

**Comment by hossinasaadi** [comment]
> version 0.3.9.2 is not working too. in first release of this script when for first time Vless implanted, i was using Vless with WS and Xray core was 1.6.1 and 1.6.0 and everything worked fine. i don't think it is relevant to using TCP or Xcore 1.4.0 to work.

**it doesn't disable inbound any more!! it prevent connections more than limit ip**

**Comment by Artin70** [comment]
> sudo x-ui update

connect-disconnect happens on the second IP for almost every 1 min. I guess this happens because the checking interval for IP limit function is set to 1 min or something like that. so the second IP can stay connected between this interval. If this is the case,     I think this doesn't work efficiently unless the interval is set to a very small number like 1 sec to disrupt the connection constantly and force the user to diconnect the second IP. I'm not sure if this works though. And if it is possible, a better solution is that the second IP stays disconnected for a longer interval like 5-10 min to force the user to disconnect the second IP.

**Comment by Dovlet241** [comment]
@hossinasaadi 
OK, i didn't know that, sorry my bad.
but i tested now and as @Artin70 said there is a problem. i can download on wifi and Cellular simultaneously without any problem. i limit it to one ip and in ip log there is one ip too.
![1](https://user-images.githubusercontent.com/63397074/200129573-27f36c0e-ad11-42f0-80c7-a64891de6d82.JPG)
![2](https://user-images.githubusercontent.com/63397074/200129710-1f697704-546c-473d-9297-4ccb9e63ef7a.jpg)

**Comment by Artin70** [comment]
> > > sudo x-ui update
> > 
> > 
> > connect-disconnect happens on the second IP for almost every 1 min. I guess this happens because the checking interval for IP limit function is set to 1 min or something like that. so the second IP can stay connected between these intervals. If this is the case, I think this doesn't work efficiently unless the interval is set to a very small number like 1 sec to disrupt the connection constantly and force the user to diconnect the second IP. I'm not sure if this works though. And if it is possible, a better solution is that the second IP stays disconnected for a longer interval like 5-10 min to force the user to disconnect the second IP.
> 
> Bro, it’s about online user, if limit set to 1 ,while Phone A connected , phone B getting disconnected! While A gone offline or its not send any packets,B can connect. And interval for check log in last version is 10s. in next test Don’t check downloading, check instagram or website with both. And let me know @Dovlet241

I get the idea, but the problem is that both A and B can stay connected with a little disruption i. e. A and B are connected then after 10 seconds (interval) one of them disconnects since 2 IPs logged and after10 seconds (interval) again both are connected since just 1 IP was connected during the last interval and this goes on and on. or based on what you said, if A doesn't send any packets for like a second then B connects and vice versa. so if the purpose is to keep out the second IP (B) as long as A is connected, it isn't practical using this method because the users stay connected and can use the connection with a minor disruption. This is what I understood from this method, please correct me if I'm wrong.

**Comment by Dovlet241** [comment]
I got it how it works. i tested with scrolling Instagram Explore simultaneously on two devices and i notice some disruption but as @Artin70 said it was very very minor.

**Comment by hossinasaadi** [comment]
> I got it how it works. i tested with scrolling Instagram Explore simultaneously on two devices and i notice some disruption but as @Artin70 said it was very very minor.

how about now? check new release @Dovlet241 @Artin70

**Comment by Artin70** [comment]
> how about now? check new release @Dovlet241 @Artin70

It's the same, connect-disconnect periodically: A connects & B disconnects --> A & B connect --> A disconnects B connects --> A & B connect.

**Comment by hossinasaadi** [comment]
> > how about now? check new release @Dovlet241 @Artin70
> 
> It's the same, connect-disconnect periodically: A connects & B disconnects --> A & B connect --> A disconnects B connects --> A & B connect.

A & B emails are different? Should be different

**Comment by Artin70** [comment]
> > > how about now? check new release @Dovlet241 @Artin70
> > 
> > 
> > It's the same, connect-disconnect periodically: A connects & B disconnects --> A & B connect --> A disconnects B connects --> A & B connect.
> 
> A & B emails are different? Should be different

sorry, I didn't get it. which email? by A & B I meant IP (device) A and IP (device) B.  both connect to the same config in which just one email could be defined.

**Comment by rezatitan7** [comment]
> > > > how about now? check new release @Dovlet241 @Artin70
> > > 
> > > 
> > > It's the same, connect-disconnect periodically: A connects & B disconnects --> A & B connect --> A disconnects B connects --> A & B connect.
> > 
> > 
> > A & B emails are different? Should be different
> 
> sorry, I didn't get it. which email? by A & B I meant IP (device) A and IP (device) B. both connect to the same config in which just one email could be defined.

Yes dear @hossinasaadi, I just updated to the latest version right now, **surprisingly it works now for me**, **BUT** it's exactly like what @Artin70 says, it connects and disconnects, it doesn't remain disconnect after a second IP connect.

**Comment by hossinasaadi** [comment]
> > > > how about now? check new release @Dovlet241 @Artin70
> > > 
> > > 
> > > It's the same, connect-disconnect periodically: A connects & B disconnects --> A & B connect --> A disconnects B connects --> A & B connect.
> > 
> > 
> > A & B emails are different? Should be different
> 
> sorry, I didn't get it. which email? by A & B I meant IP (device) A and IP (device) B. both connect to the same config in which just one email could be defined.

Sorry:/ 
I was in phone call when i reply and getting distracted. 
i test new version on 2 machine and works great. 
i think you do something wrong.

**Comment by rezatitan7** [comment]
@hossinasaadi I think you should increase the interval after a second device connects, it should get stuck and remain for as long as the second IP is connected, **I can sense the problem is coming from the feature that purges IP addresses after 1 minute.**

**Comment by rezatitan7** [comment]
@hossinasaadi Also, CPU usage skyrocketed to around 95~100% after the latest update.

**Comment by Artin70** [comment]
> Sorry:/ I was in phone call when i reply and getting distracted. i test new version on 2 machine and works great. i think you do something wrong.

just to make sure I do the instruction exactly as you said:
setting Listen IP to Server IP.
using Vmess and TCP.
IP limit = 1
xray version 1.4.0
anything else?
and CPU usage gets too high (80%) as @hossinasaadi mentioned.

**Comment by hossinasaadi** [comment]
@Artin70 yes, i remove that release. You can back to last release. 
let me tomorrow see what I can do.

**Comment by hossinasaadi** [comment]
> @hossinasaadi I think you should increase the interval after a second device connects, it should get stuck and remain for as long as the second IP is connected, **I can sense the problem is coming from the feature that purges IP addresses after 1 minute.**

Hi @rezatitan7 , you were right!. in this pull https://github.com/hossinasaadi/x-ui/pull/1 , all database will be clean and the old log will be gone. so the system let second device connect for little time.
now update to 0.3.9.4

**Comment by hossinasaadi** [comment]
> > @hossinasaadi I think you should increase the interval after a second device connects, it should get stuck and remain for as long as the second IP is connected, **I can sense the problem is coming from the feature that purges IP addresses after 1 minute.**
> 
> Hi @rezatitan7 , you were right!. in this pull #1 , all database will be clean and the old log will be gone. so the system let second device connect for little time. now update to 0.3.9.4

@rezatitan7 @Artin70 also please test ws and tcp, let me know :heart:

**Comment by Dovlet241** [comment]
Hi
i updated to 3.9.4 and tested out in different ways. set ip limit to 1 and watching YouTube in PC and monitor network activity and in same time scrolling Instagram on Phone. both device can connect without any problem. but maybe i am wrong let's other test too.

**Comment by Artin70** [comment]
> @rezatitan7 @Artin70 also please test ws and tcp, let me know ❤️

just in tcp mode it works like connect-disconnect on the second IP, each disconnection time is about 20 seconds.
by the way, is there any way to install a specific verion of x-ui other than the last version on the server?

**Comment by rezatitan7** [comment]
> 

@Artin70 I can confirm this, and also VMess does not work, only VLESS works in a connect-disconnect behavior.

**Comment by Dovlet241** [comment]
> > 
> 
> @Artin70 I can confirm this, and also VMess does not work, only VLESS works in a connect-disconnect behavior.

you tested with tcp?

**Comment by Artin70** [comment]
@hossinasaadi I installed v 0.3.8 and it had a better performance than v 0.3.9.4. maybe it's just about a different interval but it works like this: fast connect-disconnect for IP1 for about 1 min, then same thing happens for IP2. there isn't any time that both of the are onnected at the same time or at least it's so small that I didn't noticed. So maybe if the connect-disconnect time is set to a larger amount, it'll eventually make one of the user IPs diconnect itself manually since the disruption continues for a larger time (like 10 min).
Btw v 0.3.9.4 takes a higher CPU usage about 35% (for v 0.3.8 it's about 5-10 %)

**Comment by hossinasaadi** [comment]
> @hossinasaadi I installed v 0.3.8 and it had a better performance than v 0.3.9.4. maybe it's just about a different interval but it works like this: while IP2 is connected, fast connect-disconnect happens to IP1 for about 1 min, then same thing happens for IP2. there isn't any time that both of them are connected at the same time or at least it's so small that I didn't noticed. So maybe if the connect-disconnect time is set to a larger amount, it'll eventually make one of the user IPs diconnect itself manually since the disruption continues for a larger time (like 10 min). Btw v 0.3.9.4 takes a higher CPU usage about 35% (for v 0.3.8 it's about 5-10 %)

Hi @Artin70 , i customize xray core https://github.com/hossinasaadi/Xray-core , now i released version 0.4.1. see its work

**Comment by hossinasaadi** [comment]
> > @hossinasaadi I installed v 0.3.8 and it had a better performance than v 0.3.9.4. maybe it's just about a different interval but it works like this: while IP2 is connected, fast connect-disconnect happens to IP1 for about 1 min, then same thing happens for IP2. there isn't any time that both of them are connected at the same time or at least it's so small that I didn't noticed. So maybe if the connect-disconnect time is set to a larger amount, it'll eventually make one of the user IPs diconnect itself manually since the disruption continues for a larger time (like 10 min). Btw v 0.3.9.4 takes a higher CPU usage about 35% (for v 0.3.8 it's about 5-10 %)
> 
> Hi @Artin70 , i customize xray core https://github.com/hossinasaadi/Xray-core , now i released version 0.4.1. see its work. it works for all connection types.

also no need to change xray vdersion to 1.4.0 @conall1995 @Dovlet241 @rezatitan7 @Artin70

**Comment by Artin70** [comment]
> also no need to change xray vdersion to 1.4.0 in new version (0.4.1) @conall1995 @Dovlet241 @rezatitan7 @Artin70

Sorry for late reply. my server got blocked and I had to create another server. I tested 0.4.1 with vless protocol + tcp or ws. ws works better than tcp. connect-disconnect happens almost constantly on the second IP and connecting time on the second IP takes about 10 sec each time which barely happens. another advantage of this version is that the 1st IP almost never disconnects during the IP limit function. the only problem is that the 2nd IP can still use the connection despite of the constant disruption, because connect-dsiconnect happens almost every 1 sec.

**Comment by rezatitan7** [comment]
@Artin70 @hossinasaadi I tested the new release and can say **IP Blocking function works now for me**, VLESS & VMess + **WS only**. If it doesn't work, you have to set **Listen IP,** then it works decently. I haven't tested it in online games myself, but I have reports from users which they say they sometimes disconnect from their games and server has ping spikes.

**Comment by hossinasaadi** [comment]
> @Artin70 @hossinasaadi I tested the new release and can say **IP Blocking function works now for me**, VLESS & VMess + **WS only**. If it doesn't work, you have to set **Listen IP,** then it works decently. I haven't tested it in online games myself, but I have reports from users which they say they sometimes disconnect from their games and server has ping spikes.

version 0.4.3 ?

**Comment by rezatitan7** [comment]
@hossinasaadi OMG there is another release? I'm kind of afraid of updating now 😂, since it works decently now with a little bit of hiccups here and there. Dear Hossein, would you guarantee that I don't lose blocking function again?

**Comment by hossinasaadi** [comment]
Yeah I swear 😂

**Comment by hossinasaadi** [comment]
> @hossinasaadi OMG there is another release? I'm kind of afraid of updating now joy, since it works decently with a little bit of hiccups here and there. Dear Hossein, would you guarantee that I don't lose blocking function again?

in the new version, you can also set the language to English in setting

**Comment by Artin70** [comment]
> you were right. Would you be able to test the new version? 0.4.3

works like this: 2nd IP: disconnects for like 10 sec, then connects for 30 sec and sometimes connect-disconnect for 10 sec.
1st IP connection remains intact but since 0.4.1 it has download/upload status like this when network is idle:
![1st IP](https://user-images.githubusercontent.com/117419970/200738021-86e70551-3d94-413a-88b0-dc6af4c8d5f5.png)

**Comment by Artin70** [comment]
> @Artin70 @hossinasaadi I tested the new release and can say **IP Blocking function works now for me**, VLESS & VMess + **WS only**. If it doesn't work, you have to set **Listen IP,** then it works decently. I haven't tested it in online games myself, but I have reports from users which they say they sometimes disconnect from their games and server has ping spikes.

for game or usages which need stable connection and ping maybe this works but for general usage like checking instagram or telegram or even downloading files this isn't practical for now. it has to disconnect the 2nd IP constantly at least for several minutes. the IP limit function is designed to takes the chance of blocking the server IP from the government as low as possible by allowing limited IPs to connect to the server. but now this limitation doesn't work completely.

**Comment by Artin70** [comment]
> > you were right. Would you be able to test the new version? 0.4.3
> 
> works like this: 2nd IP: disconnects for like 10 sec, then connects for 30 sec and sometimes connect-disconnect for 10 sec. 1st IP connection remains intact but since 0.4.1 it has download/upload status like this when network is idle: ![1st IP](https://user-images.githubusercontent.com/117419970/200738021-86e70551-3d94-413a-88b0-dc6af4c8d5f5.png)

@hossinasaadi Update:  for some reason, I stopped the panel, deleted my database and started it again, built a new **vless+ws** inbound and now it works almost fine. the 2nd IP is disconnected almost all the time, connect or connect-disconnect for like 10 sec which happens periodically (maybe about every 2 mins).
the cpu usage goes higher from 5% to 20% sometimes and idle network usage on 1st IP is as the graph that I posted in the last comment.

so generally it works fine. maybe a larger disconnection time on the 2nd IP and CPU usage optimization can be done to make it more efficient.

**Comment by Argo160** [comment]
> > ![Capture](https://user-images.githubusercontent.com/116899376/200838698-23b68733-7d05-4715-86ac-529fb3252895.PNG) Did i add the codes correctly?
> 
> yes.

Thank you.
Could we use same email address for all the inbound list?
and i cant find what is the use of acceptProxyProtocol.
Anyway thanks for the great job bro

**Comment by hossinasaadi** [comment]
> > > ![Capture](https://user-images.githubusercontent.com/116899376/200838698-23b68733-7d05-4715-86ac-529fb3252895.PNG) Did i add the codes correctly?
> > 
> > 
> > yes.
> 
> Thank you. Could we use same email address for all the inbound list? and i cant find what is the use of acceptProxyProtocol. Anyway thanks for the great job bro

no should be different email address. if it's useful to you give repo star :+1:

**Comment by Argo160** [comment]
> > > > ![Capture](https://user-images.githubusercontent.com/116899376/200838698-23b68733-7d05-4715-86ac-529fb3252895.PNG) Did i add the codes correctly?
> > > 
> > > 
> > > yes.
> > 
> > 
> > Thank you. Could we use same email address for all the inbound list? and i cant find what is the use of acceptProxyProtocol. Anyway thanks for the great job bro
> 
> no should be different email address. if it's useful to you give repo star +1

I did already and gladly. 
wish i could give more stars.

**Comment by Artin70** [comment]
after 0.4.4 IP limit doesn't work and no IP is shown when when I click on the IP log field. does anyone else has this problem?

**Comment by hossinasaadi** [comment]
> after 0.4.4 IP limit doesn't work and no IP is shown when I click on the IP log field. does anyone else have this problem?

read the hint. "click on the field to get IP" and also limit works

**Comment by void1995** [comment]
@hossinasaadi  how we can use previous branch that blocked config with extra connections not just drop them?

**Comment by MiladIT01** [comment]
@hossinasaadi Could you please tell me how can i change cron times?what's the file path?

**Comment by shynm** [comment]
@hossinasaadi I test new x-ui version.
It's not working correctly.
Connected IPs show in IP Log Pannel but in same time both of them are connect.
I check this for more than 10 minutes and noting happen.

I Reboot server but not working too.
I uninstall x-ui completely and install your 0.4.4 Version again but not working too.
I test this in my pc (with wifi connection) and my phone (with mobile data).

**Comment by MataAzi** [comment]
@hossinasaadi Can you please add some version that disable User Account? Or Add Method To Rest Api So We Can See how many ip's connected then we can do anything with account. 

Thanks For Great Work. You are a real hero :)

**Comment by shynm** [comment]
@hossinasaadi 
How Can I disable Inbounds when connection more than IP limitation amount? (version 0.4.4)
What change should I give in which line of code?

**Comment by hhamed1989** [comment]
Hello, I use WS method. And I also filled Listen IP with server IP. It used to work correctly in the beginning, but after the last update to the new version, even though nothing has changed in the settings, there is a problem and the IP limit is not applied. I check the access log, both IPs are listed and the panel shows that 2 IPs are connected. But the limit is not applied.
![v2ray](https://user-images.githubusercontent.com/38720987/204532670-aa494eb6-0dc0-4382-99d8-bf8c262b9e7e.jpg)
