### ISSUE TITLE
x-ui and xray stopped

### ISSUE THREAD

**Issue by aliasqar** [hossinasaadi/x-ui#80]
hello
The x-ui and xray stopped suddenly and gives an error when starting

**Comment by NoRRt** [comment]
I have this problem too

**Comment by hossinasaadi** [comment]
Hi @NoRRt @aliasqar , `x-ui status` and copy output here

**Comment by amihos** [comment]
> hello
> The x-ui and xray stopped suddenly and gives an error when starting
> 

This can happen if you create a bad (wrong) inbound. Check them.
