### ISSUE TITLE
ip limit

### ISSUE THREAD

**Issue by AwJHub** [hossinasaadi/x-ui#81]
Hi, Read the other issue solving ip limit issue but still i get this error while saving x-ray config
![image](https://user-images.githubusercontent.com/76947375/202841681-3b9e7f31-d45d-4e65-bbcb-708141de4228.png)

**Comment by mory** [comment]
Just remove { before "api"

**Comment by AwJHub** [comment]
👀Well.. yeah..

is there any fix for tunneled v2tay ip limit?

**Comment by hossinasaadi** [comment]
> eyesWell.. yeah..
> 
> is there any fix for tunneled v2ray ip limit?

actually, there is no way to do that right now!
I close the issue so if you have any problems, open it again.
