### ISSUE TITLE
xray state: Not Running

### ISSUE THREAD

**Issue by Danaserver** [hossinasaadi/x-ui#84]
سلام
بعد از اضافه کردن چند inbounds به مشکل زیر برخوردم
Panel state: Not Running
Start automatically: Yes
xray state: Not Running
دیگه ریستارت هم نمیشه
داخل پنل هم میزنه  xray Status: error

**Comment by hossinasaadi** [comment]
x-ui status and send out put here

**Comment by hossinasaadi** [comment]
https://github.com/hossinasaadi/x-ui/issues/80#issuecomment-1320863167

**Comment by amihos** [comment]
If you create an inbound that is wrong or corrupted, this can happen. Check your inbounds. (Maybe delete them one by one to find the devil)

**Comment by Danaserver** [comment]
مشکل این بود که برای inbounds هم listen ip سرور رو زده بودم

**Comment by hossinasaadi** [comment]
so i close the issue,

> مشکل این بود که برای inbounds هم listen ip سرور رو زده بودم
