### ISSUE TITLE
مشکل در یورزنیم و پسورد پیشفرض

### ISSUE THREAD

**Issue by mehdikhody** [hossinasaadi/x-ui#85]
سلام. قبلا هنگام نصب یا بروزرسانی اگر فیلد یوزنیم و پسورد و پورت را خالی می گذاشتیم به صورت پیشفرض می شد admin و admin، اما الان اگر خالی باشه همون خالی ثبت میشه.

**Comment by hossinasaadi** [comment]
actually it's not a bug :/
