### ISSUE TITLE
مشکل اضافه نشدن headertype در لینک vless

### ISSUE THREAD

**Issue by samaelleo** [hossinasaadi/x-ui#86]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

وقتی کانکشن روی vless و پروتکل tcp  میزاریم و هدر http رو فعال میکنیم در لینک هدر اضافه نمیشه مثل کانفیگ vmess

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by hossinasaadi** [comment]
fixed in the new version, thanks for reporting @samaelleo
