### ISSUE TITLE
حجم مصرفی کلاینت ها درست نیست

### ISSUE THREAD

**Issue by Jolge100** [hossinasaadi/x-ui#87]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

با تشکر از کمکی که می کنی یه مشکلی که متاسفانه وجود داره حجم مصرفی کلاینت ها رو درست محاسبه نمی کنه
حجم کل رو درست محاسبه می کنه اما حجم هر یوزر رو حساب نمی کنه که این باعث می شه محدودیت حجمی که برای هر کلاینت می ذاریم بی تاثیر باشه
ممنونم
### Version of x-ui

1.6.4

### x-ui log or xray log

dont have logs
![1](https://user-images.githubusercontent.com/118624183/202864123-9f6b94e8-40de-48fc-a80c-73a2b0c0b110.jpg)

1. correct
2.incorrect

**Comment by aliasqar** [comment]
من هم همین مشکل رو دارم

**Comment by IamYousef** [comment]
![image](https://user-images.githubusercontent.com/22050119/202868592-faac0698-fe6a-44ee-8ef4-b507cdecfd1a.png)
![image](https://user-images.githubusercontent.com/22050119/202868598-0e98dde8-ffc3-4113-b0ee-cc7acb1195f7.png)
منم همین مشکل رو دارم

**Comment by Mo3M** [comment]
X-UI reports unreal traffics(multiple-folds) with [vless+sw+cdn+nginx]
=============================================

No matter which flavors of x-ui I've been using the traffic in the panel is wrong.
I did some testings with speedtest.net and found out that with the configuration in the title the reported traffic was way too much higher than actual used traffic.
I reset the traffic in the panel and tried speedtest(ookla) app on mobile.
The data used during upload/download was 24MB/78MB but the panel showed it was 32MB/320MB.

**Comment by hossinasaadi** [comment]
thanks for reporting @aliasqar @IamYousef @Mo3M @Jolge100 , please update to 0.5.1 with `x-ui update` , see it fixed

**Comment by Jolge100** [comment]
thanks it is fix now
so thanks

**Comment by Mo3M** [comment]
> # X-UI reports unreal traffics(multiple-folds) with [vless+ws+cdn+nginx]
> No matter which flavors of x-ui I've been using the traffic in the panel is wrong. I did some testings with speedtest.net and found out that with the configuration in the title the reported traffic was way too much higher than actual used traffic. I reset the traffic in the panel and tried speedtest(ookla) app on mobile. The data used during upload/download was 24MB/78MB but the panel showed it was 32MB/320MB.

Thanks but the problem still persists with the mentioned configuration.
