### ISSUE TITLE
کاربر چطور میتونه ترافیک باقی مانده و تایم اکسپایر رو ببینه ؟

### ISSUE THREAD

**Issue by SepidGsm** [hossinasaadi/x-ui#89]
کاربر چطور میتونه ترافیک باقی مانده و تایم اکسپایر رو ببینه ؟
میشه پیجی کد نویسی کنین کاربر با وارد کردن پورت جزئیات اکانتشو مشاهده کنه ؟

**Comment by IamYousef** [comment]
نمیتونه ببینه درحال حاضر ولی ایده ی خوبیه
می تونیم رو یه پورت دیگه مثلا 54123 یه صفحه وب دیگه بالا بیاریم که با وارد کردن کانفیگ، اطلاعات جامعه ای ازش نمایش بده

**Comment by SepidGsm** [comment]
برای اینکار دوستان ربات تلگرامی بالا اورده
سورس همچین رباتی رو دارین ؟

**Comment by alirezax5** [comment]
با استفاده از api میتونید داخل یک صفحه یا ربات به کاربر نمایش بدید.

https://github.com/hossinasaadi/x-ui/files/10012490/X-UI.API.postman_collection3.zip

**Comment by SepidGsm** [comment]
دوست عزیز متاسفانه با api کار نکردم اگر ممکنه ساده تر توضیح بدین و یا سورس صفحه رو زحمتشو بکشین

**Comment by alirezax5** [comment]
> دوست عزیز متاسفانه با api کار نکردم اگر ممکنه ساده تر توضیح بدین و یا سورس صفحه رو زحمتشو بکشین


در حال حاضر با آدرس های زیر میتونی اطلاعات هارو دریافت کنی :
ip:port/xui/API/inbounds/
یا یک ورودی خاص رو گت کنی
ip:port/xui/API/inbounds/id

بعد از گت میتونی از لیست کلاینت ها که توی settings هستش کلاینت هارو دریافت کنی و بررسی کنی چقدر حجم داره و چقدر زمانش مونده.

در حال حاضر این راه موجوده جز اینکه در آینده توسعه دهنده دریافت آمار براساس ایمیل رو فراهم کنه.

منطقی ترین کار الان اینه هر نیم ساعت یکبار لیست کامل رو بگیری و داخل یک دیتابیس براساس ایمیل ذخیره کنی

**Comment by hossinasaadi** [comment]
@IamYousef @SepidGsm install new version and check telegram bot
