### ISSUE TITLE
I need the previous version that had only VMess support

### ISSUE THREAD

**Issue by rezatitan7** [hossinasaadi/x-ui#9]
My server is in a great danger of being shared and exposed to everyone right now, IP/Device limitation does not work at all on your latest version, please provide me with the previous version that had support only for VMess, thank you.

**Comment by hossinasaadi** [comment]
Hi @rezatitan7, please install the new version and let me know

**Comment by rezatitan7** [comment]
Tested it, this time limitation worked for a brief moment (a couple of seconds) and then stopped blocking excess IP all together after that.

**Comment by hossinasaadi** [comment]
> Tested it, this time limitation worked for a brief moment (a couple of seconds) and then stopped blocking excess IP all together after that.

Look, when you set a limit to 1 and 2 IPs connected, one of them will drop. the system prevents other connections if more than limit number. so if you don't use your first phone, the second phone can connect.

**Comment by rezatitan7** [comment]
Still doesn't work, I set IP Count Limit to 1, connected my phone through mobile data, and my PC which is ADSL, 2 IPs are connected simultaneously right now, yet nothing is blocked for neither of them.

Could you please provide me with the previous version that had VMess only? That one worked very decently with no problem whatsoever.

**Comment by rezatitan7** [comment]
Also, there is a bug that it shows every connected client IPs in every single one of the inbound profiles, For example, if I connect to profile A, I can see my IP address on profile B too, Client IP Log is not 'per created profiles', it shows all connected IPs regardless of inbound profiles.
