### ISSUE TITLE
Trojan برای ip محدود کردن 

### ISSUE THREAD

**Issue by Farbodhjt** [hossinasaadi/x-ui#92]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام وقت بخیر آیا قابلیت لیمیت کردن ip برای trojan هم وجود داره یا فقط Vmess و Vless کار میکنه؟
سوال دوم اینکه نیاز به نصب مجزا xray  وجود داره ؟ یا این اسکریپت خودش core ها Trojan رونصب میکنه؟
سوال سوم باید از قبل v2-ui روی سرور نصب باشه؟
ممنون از وقتی که گذاشتید

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by alirezax5** [comment]
سلام درمورد سوال اول در حال حاض. که نسخه 0.5.1 منتشر شده محدود کردن آیپی برای تروجان فعال نشده

سوم دوم خیر ، اسکریپت رو نصب کنید خودش به همراه اسکپریته و شما فقط کافیه یک ورودی( کانفیگ) بسازید

سوال سوم خیر نیاز نیست ،فقط x-ui رو نصب کنید.

**Comment by Farbodhjt** [comment]
ممنون ازتون به خاطر این پرسیدم چون داخل Features ها نوشته بود
Supported protocols: vmess, vless, trojan, shadowsocks, dokodemo-door, socks, http
مشخص هست کلا کی اضافه بشه؟

**Comment by alirezax5** [comment]
> ممنون ازتون به خاطر این پرسیدم چون داخل Features ها نوشته بود Supported protocols: vmess, vless, trojan, shadowsocks, dokodemo-door, socks, http مشخص هست کلا کی اضافه بشه؟

خواهش

اینو خود توسعه دهنده باید پاسخ بده @hossinasaadi 

احتمالا داخل اهدافش هست.

**Comment by hossinasaadi** [comment]
> ممنون ازتون به خاطر این پرسیدم چون داخل Features ها نوشته بود Supported protocols: vmess, vless, trojan, shadowsocks, dokodemo-door, socks, http مشخص هست کلا کی اضافه بشه؟

Hi @Farbodhjt , the multi-user version and IP limit just added for Vmess & Vless , maybe in future we add for other protocols
