### ISSUE TITLE
Review `89a7d93` commit

### ISSUE THREAD

**Issue by ysmoradi** [hossinasaadi/x-ui#93]
Could you please briefly explain what's going on in this commit?
https://github.com/hossinasaadi/x-ui/commit/89a7d933e41972c7e1ead17913fc5fc2adfb4385
Thanks in advance

**Comment by hossinasaadi** [comment]
Hi @ysmoradi , the base xray core when I made fork from vaxilu was 1.4.1 and it wasn't customized!, so I customize the Xray core for IP limit that you can see on https://github.com/hossinasaadi/Xray-core , and for developers that pull my fork and develop it, they get some error. so I think that is clear. thanks for your attention :)

**Comment by hossinasaadi** [comment]
Hi @ysmoradi , the base xray core when I made fork from vaxilu was 1.4.1 and it wasn't customized!, so I customize the Xray core for IP limit that you can see on https://github.com/hossinasaadi/Xray-core , and for developers that pull my fork and develop it, they get some error. so I think that is clear. thanks for your attention :)

**Comment by ysmoradi** [comment]
If I understand correctly, if we don't need the IP restrictions, we can use the original version, right?

**Comment by hossinasaadi** [comment]
right, but if you want to run the original version with this source you should make some changes in process.go to line 165

**Comment by hossinasaadi** [comment]
i close the issue as solved , let me know if you have problem
