### ISSUE TITLE
Add more info about wallet addresses

### ISSUE THREAD

**Issue by ysmoradi** [hossinasaadi/x-ui#95]
```
TRC20: TDam6uh8ctLJuz8Y3rRk4t5pLikQvtpvJE
ETH: 0x256ddA590c35638fA4B3a25Ec4544Db087ceE826
```
What can be sent to the first address? TRX? USDT? anything else?
What about the 2nd one? Is it Ether? Dai? USDT? whatever?

**Comment by hossinasaadi** [comment]
USDT TRC20: `TDam6uh8ctLJuz8Y3rRk4t5pLikQvtpvJE`

Ether ETH: `0x256ddA590c35638fA4B3a25Ec4544Db087ceE826`

thanks btw :)
