### ISSUE TITLE
مشکل در نصب

### ISSUE THREAD

**Issue by moslem2013** [hossinasaadi/x-ui#98]
### Welcome

- [X] Yes, I'm using the latest major release. Only such installations are supported.
- [X] Yes, I'm using the supported system. Only such systems are supported.
- [X] Yes, I have read all WIKI document,nothing can help me in my problem.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, log, etc).

### Description of the problem,screencshot would be good

سلام وقت بخیر
هنگام نصب با این خطا مواجه میشم و بعد از وارد کردن آدرس پنل وارد پنل نمیشه 
ممنون میشم راهنمایی بفرمایید

/usr/local/x-ui/x-ui: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/x-ui/x-ui)
account name and password set down!
/usr/local/x-ui/x-ui: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/x-ui/x-ui)

### Version of x-ui

<details>

```console
$ x-ui version
# Paste output here
```

</details>

### x-ui log or xray log

<details>

```console
# paste log here
```

</details>

**Comment by hossinasaadi** [comment]
Please search in issues first!

**Comment by moslem2013** [comment]
سلام چک کردم چیزی پیدا نکردم 
توی این نسخه که در ادرس زیر هستش در ورژن 0.1 این مشکل بوده که حل کردن
https://github.com/NidukaAkalanka/x-ui-english
الان همین مشکل رو با اسکریپتی گذاشتید دارم اگر امکانش هست بررسی بفرمایید و مشکل رو حل کنید ممنون میشم

**Comment by hossinasaadi** [comment]
> GLIBC_2.28

install latest version it fixed @moslem2013

**Comment by moslem2013** [comment]
خیلی ممنون مشکل برطرف شد
