### ISSUE TITLE
تانل کردن دو سرور

### ISSUE THREAD

**Issue by bestkilleriranlod** [hossinasaadi/x-ui#99]
سلام
دو سرور ایران و خارج به همدیگه تانل کردم
روی ایران Haproxy و روی خارج v2
فقط مشکل اینجاست که ای پی کاربر بر نمیگرده به پنل v2
ممنون میشم راهنمایی کنید

**Comment by bestkilleriranlod** [comment]
اگر توی haproxy بشه تعریف کرد که هر با هر پورت یک کاربر فقط اجازه دسترسی بده خیلی بهتر

**Comment by hossinasaadi** [comment]
Hi @bestkilleriranlod , it's not an issue , so please open discussion and talk about these things! ty
